/**
 * Open Banking Gateway Tpp Authentication API
 * This API provides PSU login and registration functionality on TPP side.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GeneralError { 
    code?: string;
    message?: string;
}

