localapp:
  schema:
    # seem to be shared
    name: consent

spring:
  datasource:
    url: ${common.db.url}
    username: testonlinebanking
    password: testonlinebanking
    driver-class-name: ${common.db.driver}
  liquibase:
    enabled: true
server:
  port: ${common.apps.local.onlinebanking.port}

cms:
  url: ${common.apps.mapping.consentmgmt}
ledgers:
  url: ${common.apps.mapping.ledgersapp}
oba:
  url: ${common.apps.mapping.onlinebanking}
self:
  url: ${common.apps.mapping.onlinebanking}
xs2a:
  url: ${common.apps.mapping.ledgersgateway} # alias port 8089 in dev

online-banking-scauiredirect: true

# To verify
server_key: 12345