localapp:
  schema:
    name: consent

spring:
  datasource:
    url: ${common.db.url}
    username: testconsentmgmt
    password: testconsentmgmt
    driver-class-name: ${common.db.driver}
  liquibase:
    enabled: true
server:
  port: ${common.apps.local.consentmgmt.port}

server_key: secret123

aspsp-profile:
  baseurl: ${common.apps.mapping.aspsp}/api/v1

# To verify:
skip_ssl_certificate_verification: true
used-non-recurring-consent-expiration:
  cron:
    expression: 0 0 * * * *