@startuml

autonumber "<b><color blue>[Login-000]</color></b>"
actor psu

box "PsuUserAgent" #LightGray
    participant "FinTechUI" as FinTechUI
    'participant "ConsentAuthorisationUI" as ConsentAuthorisationUI
    'participant "OnlineBankingUI" as OnlineBankingUI
end box
box "FinTechDC" #DarkSeaGreen
    participant "FinTechApi" as FinTechApi
end box
box "TppDC" #LightGray
    'participant "TppBankingApi" as TppBankingApi
    'participant "TppBankSearchApi" as TppBankSearchApi
    'participant "ConsentAuthorisationApi" as ConsentAuthorisationApi

    'participant "RedirectSessionStoreApi" as RedirectSessionStoreApi
    'participant "BankingProtocolSelector" as BankingProtocolSelector
    'participant "BankingProtocol" as BankingProtocol
end box
box "AspspDC" #LightSkyBlue
	'participant "AspspBankingApi" as AspspBankingApi
    'participant "OnlineBankingApi" as OnlineBankingApi
end box

== PSU establishes a session with the FinTech API : call[header](body)<params> return code[header](body) ==
psu -> FinTechUI ++ : loadFinTechApplication()
return displayLoginUI()
psu -> FinTechUI ++ : enterLoginData(username,password)
FinTechUI -> FinTechApi ++ : login[](loginRequest)<>
return 200_UserProfile[cookies=SessionCookie,X-XSRF-TOKEN=xsrfToken](UserProfile)
FinTechUI -> FinTechUI : parseAndStoreXsrfToken()
return displayBankSearchScreen()
@enduml