@startuml

autonumber "<b><color blue>[Search-000]</color></b>"
actor psu

box "PsuUserAgent" #LightGray
    participant "FinTechUI" as FinTechUI
    'participant "ConsentAuthorisationUI" as ConsentAuthorisationUI
    'participant "OnlineBankingUI" as OnlineBankingUI
end box
box "FinTechDC" #DarkSeaGreen
    participant "FinTechApi" as FinTechApi
end box
box "TppDC" #LightGray
    'participant "BankingApi" as BankingApi
    participant "TppBankSearchApi" as TppBankSearchApi
    'participant "ConsentAuthorisationApi" as ConsentAuthorisationApi

    'participant "RedirectSessionStoreApi" as RedirectSessionStoreApi
    'participant "BankingProtocolSelector" as BankingProtocolSelector
    'participant "BankingProtocol" as BankingProtocol
end box
box "AspspDC" #LightSkyBlue
	'participant "AspspBankingApi" as AspspBankingApi
    'participant "OnlineBankingApi" as OnlineBankingApi
end box

== PSU searches a bank by keyword : call[header](body)<params> return code[header](body) ==

psu -> FinTechUI ++ : loadFinTechSeachScreen()
return displaySearchScreen()
psu -> FinTechUI ++ : enterKeyword(keyword)
loop while(furtherKeyWords)
FinTechUI -> FinTechApi ++ : incrementalBankSearch[](keyword)<>
FinTechApi -> TppBankSearchApi ++ : incrementalBankSearch[](keyword)<>
return 200_OK[](List<BankDescriptor>)
return 200_OK[](List<BankDescriptor>)
return display(List<BankDescriptor>)
end
@enduml