@startuml

autonumber "<b><color blue>[00]"
actor psu

box "PsuUserAgent" #LightGray
    participant "FinTechUI" as FinTechUI
    participant "LuceneSearch" as LuceneSearch
    'participant "TppConsentSessionUI" as TppConsentSessionUI
    'participant "AspspConsentSessionUI" as AspspConsentSessionUI
end box
box "FinTechDC" #DarkSeaGreen
    participant "FinTechApi" as FinTechApi
end box
box "TppDC" #LightGray
    'participant "TppBankingApi" as TppBankingApi
    participant "TppBankSearchApi" as TppBankSearchApi
    'participant "TppConsentSessionApi" as TppConsentSessionApi

    'participant "RedirectSessionStoreAPI" as RedirectSessionStoreAPI
    'participant "BankingProtocolSelector" as BankingProtocolSelector
    'participant "BankingProtocol" as BankingProtocol
end box
box "AspspDC" #LightSkyBlue
	'participant "AspspBankingApi" as AspspBankingApi
    'participant "AspspConsentSessionApi" as AspspConsentSessionApi
end box

== PSU searches a bank by keyword : call[header](body)<params> return code[header](body) ==

psu -> FinTechUI ++ : loadFinTechSeachScreen()
FinTechUI -> FinTechApi ++ : GET:bankSearchIndex[]()<discriminator>
FinTechApi -> TppBankSearchApi ++ : GET:bankSearchIndex[]()<discriminator>
return 200_OK[](BankSearchIndex)
return 200_OK[](BankSearchIndex)
return displaySearchScreen()
psu -> FinTechUI ++ : enterKeyword(keyword)
loop while(furtherKeyWords)
FinTechUI -> LuceneSearch ++ : search(keyword)
LuceneSearch -> LuceneSearch : search(keyWord,BankSearchIndex)
return List<BankDescriptor>
return display(List<BankDescriptor>)
end
@enduml