@startuml

autonumber "<b><color blue>[00]"
actor psu

box "PsuUserAgent" #LightGray
    participant "FinTechUI" as FinTechUI
    'participant "TppConsentSessionUI" as TppConsentSessionUI
    'participant "AspspConsentSessionUI" as AspspConsentSessionUI
end box
box "FinTechDC" #DarkSeaGreen
    participant "FinTechApi" as FinTechApi
end box
box "TppDC" #LightGray
    participant "TppBankingApi" as TppBankingApi
    'participant "TppBankSearchApi" as TppBankSearchApi
    'participant "TppConsentSessionApi" as TppConsentSessionApi

    participant "RedirectSessionStoreApi" as RedirectSessionStoreApi
    participant "BankingProtocol" as BankingProtocol
end box
box "AspspDC" #LightSkyBlue
	participant "AspspBankingApi" as AspspBankingApi
    'participant "AspspConsentSessionApi" as AspspConsentSessionApi
end box

== Initiate consent upon PSU transaction display request : call[header](body)<params> return code[header](body) ==

FinTechUI --> psu : displayBankProfile(BankProfile)
psu -> FinTechUI ++ : listBankAccounts(BankProfile)
FinTechUI -> FinTechApi ++ : listBankAccounts[Psu2FinTechLoginSessionCookie,\nUserAgentContext](BankProfile,AisConsentSpec)<>
FinTechApi -> TppBankingApi ++ : listBankAccounts[UserAgentContext,\nFinTech2TppConsentSession]\n(BankProfile,AisConsentSpec)<>
TppBankingApi -> TppBankingApi : FinTech2TppConsentSession.tppConsentSession()\n:TppConsentSession
TppBankingApi -> TppBankingApi : BankProfile.bankingProtocol():BankingProtocol
TppBankingApi -> BankingProtocol ++ : listBankAccounts[UserAgentContext, TppConsentSession]\n(BankProfile, AisConsentSpec) 

alt TppConsentSession.noConsentPresent()
    BankingProtocol -> AspspBankingApi ++ : initiateConsent[UserAgentContext,\nTpp2AspspContext](AisConsent) 
    return 200_OK(Tpp2AspspConsentSession,\nAspspRedirectInfo)
    BankingProtocol -> BankingProtocol : Tpp2AspspConsentSession\n.tppConsentSession():TppConsentSession
    return 200_OK(TppConsentSession, AspspRedirectInfo)
    TppBankingApi -> RedirectSessionStoreApi ++ : redirectSession(TppConsentSession, exp)
    RedirectSessionStoreApi -> RedirectSessionStoreApi : createEncryptStoreRedirectSession\n(TppConsentSession):redirectCode
    return 200_OK[](redirectCode)<>
    TppBankingApi -> TppBankingApi : TppConsentSession.finTechSession()\n:FinTech2TppConsentSession
    return 200_Ok(FinTech2TppConsentSession,\nTppConsentSessionApi\n.entryPoint()<redirectCode>)
    return redirect302[TppConsentSessionApi.entryPoint()<redirectCode>,\nPsu2FintechLoginSessionCookie]()
else TppConsentSession.consentPresent()
    activate BankingProtocol
    BankingProtocol -> AspspBankingApi ++ : listOfAccounts[UserAgentContext,\nTpp2AspspContext](AisConsent) 
    return 200_OK[](BankAccounts)
    BankingProtocol --> TppBankingApi ++: 200_OK[](BankAccounts)
    deactivate BankingProtocol
    TppBankingApi --> FinTechApi ++ : 200_OK[](BankAccounts)
    deactivate TppBankingApi
    FinTechApi --> FinTechUI : 200_OK[Psu2FinTechLoginSessionCookie](BankAccounts)
    deactivate FinTechApi
    return displayListOfAccounts(BankAccounts)
end
@enduml
