@startuml

autonumber 10 10 "<b><color blue>[InitConsent-000]</color></b>"
actor psu

box "PsuUserAgent" #LightGray
    participant "FinTechUI" as FinTechUI
    'participant "ConsentAuthorisationUI" as ConsentAuthorisationUI
    'participant "OnlineBankingUI" as OnlineBankingUI
end box
box "FinTechDC" #DarkSeaGreen
    participant "FinTechApi" as FinTechApi
end box
box "TppDC" #LightGray
    participant "TppBankingApi" as TppBankingApi
    'participant "TppBankSearchApi" as TppBankSearchApi
    'participant "ConsentAuthorisationApi" as ConsentAuthorisationApi

    participant "BankingProtocol" as BankingProtocol
    participant "RedirectSessionStoreApi" as RedirectSessionStoreApi
end box
box "AspspDC" #LightSkyBlue
	participant "AspspBankingApi" as AspspBankingApi
    'participant "OnlineBankingApi" as OnlineBankingApi
end box

== Initiate consent upon PSU transaction display request : call[header](body)<params> return code[header](body) ==

FinTechUI --> psu : displayBankServices(BankProfile)
psu -> FinTechUI ++ : selectService\n"listTransactions(BankProfile)"
FinTechUI -> FinTechApi ++ : listTransactions[FinTechLoginSessionCookie,\nUserAgentContext](BankProfile,ListTransactionsSpec)<>
autonumber 31 1 "<b><color blue>[InitConsent-000]"
FinTechApi -> FinTechApi : psuConsentSession\n(FinTechLoginSessionCookie,\nBankProfile,ListTransactionsSpec)<>
autonumber 40 1 "<b><color blue>[InitConsent-000]"
FinTechApi -> TppBankingApi ++ : listTransactions[UserAgentContext,\nPsuConsentSession,FinTechContext]\n(BankProfile,ListTransactionsSpec)<>
autonumber 41 1 "<b><color blue>[InitConsent-000]"
TppBankingApi -> TppBankingApi : BankProfile.bankingProtocol():BankingProtocol
autonumber 50 1 "<b><color blue>[InitConsent-000]"
TppBankingApi -> BankingProtocol ++ : listTransactions[UserAgentContext, PsuConsentSession]\n(BankProfile, ListTransactionsSpec) 

autonumber 51 1 "<b><color blue>[000]"
BankingProtocol -> BankingProtocol : PsuConsentSession.tppConsentSession()\n:TppConsentSession
alt TppConsentSession.noConsentPresent()
    autonumber 60 1 "<b><color blue>[InitConsent-000]"
    BankingProtocol -> AspspBankingApi ++ : initiateConsent[UserAgentContext,\nTppContext](AisConsent) 
    return 200_OK(TppConsentSession,\nAspspRedirectInfo)
    BankingProtocol -> RedirectSessionStoreApi ++ : redirectSession(TppConsentSession, exp)
    RedirectSessionStoreApi -> RedirectSessionStoreApi : createEncryptStoreRedirectSession\n(TppConsentSession):redirectCode
    return 200_OK[](redirectCode)<>
    BankingProtocol -> BankingProtocol : TppConsentSession.psuConsentSession()\n:PsuConsentSession
    return 200_OK(PsuConsentSession, AspspRedirectInfo)
    return 200_Ok(PsuConsentSession,\nConsentAuthorisationApi\n.auth<redirectCode>)
    FinTechApi -> FinTechApi : finTechConsentSessionCookie(PsuConsentSession,\nfinTechConsentSessionState):FinTechConsentSessionCookie
    return redirect302[ConsentAuthorisationApi.auth<redirectCode,\nfinTechConsentSessionState>,\nFinTechConsentSessionCookie]()
else TppConsentSession.consentPresent()
    autonumber 71 1 "<b><color blue>[InitConsent-000]"
    activate BankingProtocol
    BankingProtocol -> AspspBankingApi ++ : listOfTransactions[UserAgentContext,\nTppContext](AisConsent) 
    return 200_OK[](Transactions)
    BankingProtocol --> TppBankingApi ++: 200_OK[](Transactions)
    deactivate BankingProtocol
    TppBankingApi --> FinTechApi ++ : 200_OK[](Transactions)
    deactivate TppBankingApi
    FinTechApi --> FinTechUI : 200_OK[FintechLoginSessionCookie](Transactions)
    deactivate FinTechApi
    return displayListOfTransactions(Transactions)
end
@enduml
