@startuml

autonumber 10 10 "<b><color blue>[InitConsent-000]</color></b>"
actor psu

box "PsuUserAgent" #LightGray
    participant "FinTechUI" as FinTechUI
    'participant "ConsentAuthorisationUI" as ConsentAuthorisationUI
    'participant "OnlineBankingUI" as OnlineBankingUI
end box
box "FinTechDC" #DarkSeaGreen
    participant "FinTechApi" as FinTechApi
end box
box "TppDC" #LightGray
    participant "TppBankingApi" as TppBankingApi
    'participant "ConsentAuthorisationApi" as ConsentAuthorisationApi
    participant "BankingProtocolFacade" as BankingProtocolFacade
    participant "TppBankSearchApi" as TppBankSearchApi

    participant "BankingProtocol" as BankingProtocol
    participant "RedirectSessionStoreApi" as RedirectSessionStoreApi
end box
box "AspspDC" #LightSkyBlue
	participant "AspspBankingApi" as AspspBankingApi
    'participant "OnlineBankingApi" as OnlineBankingApi
end box

== Initiate consent upon PSU transaction display request : call[header](body)<params> return code[header](body) ==

FinTechUI --> psu : displayBankServices(BankProfile)
psu -> FinTechUI ++ : selectService(listAccounts)
FinTechUI -> FinTechApi ++ : GET:listAccounts\n[SessionCookie,X-XSRF-TOKEN]()<bank-id>
autonumber 40 1 "<b><color blue>[InitConsent-000]"
FinTechApi -> TppBankingApi ++ : listAccounts\n[UserAgentContext,\nFintech-User-ID:psu-id@fintech,\nService-Session-ID:service-session-id,\nBank-ID:bank-id,\nFintech-Redirect-URL-OK:url,\nFintech-Redirect-URL-NOK:url,\nAuthorization:FinTechContext]()<>
autonumber 41 1 "<b><color blue>[InitConsent-000]"
TppBankingApi -> TppBankingApi : checkAuthorization(FinTechContext):finTechId
TppBankingApi -> BankingProtocolFacade ++ : listAccounts\n(UserAgentContext,\nFintech-User-ID:psu-id@fintech,\nService-Session-ID:service-session-id,\nBank-ID:bank-id,\nFintech-Redirect-URL-OK:url,\nFintech-Redirect-URL-NOK:url,\nfinTechId)
BankingProtocolFacade -> TppBankSearchApi ++ : findBankingProtocol(ServiceSessionId, BankId, "listAccounts")
return BankingProtocol
autonumber 50 1 "<b><color blue>[InitConsent-000]"
BankingProtocolFacade -> BankingProtocol ++ : listAccounts(UserAgentContext,\nFintech-User-ID:psu-id@fintech,\nService-Session-ID:service-session-id,\nBank-ID:bank-id,\nFintech-Redirect-URL-OK<>:url,\nFintech-Redirect-URL-NOK:url,\nfinTechId)

autonumber 51 1 "<b><color blue>[000]"
BankingProtocol -> BankingProtocol : loadMatchingConsent(Fintech-User-ID:psu-id@fintech,\nService-Session-ID:service-session-id,\nBank-ID:bank-id,\nfinTechId)\n:TppConsentSession
BankingProtocol -> BankingProtocol : storeServiceSession(service-session-id, ServiceSession, TppConsentSession):service-session-key
alt TppConsentSession.noConsentPresent()
    autonumber 60 1 "<b><color blue>[InitConsent-000]"
    'BankingProtocol -> AspspBankingApi ++ : initiateConsent[UserAgentContext,\nTppContext](AisConsent) 
    'return 200_OK(TppConsentSession,\nAspspRedirectInfo)
    BankingProtocol -> BankingProtocol : newAuthSession(service-session-id,\nservice-session-key, exp):auth-id,redirectCode // sign&encrypted
    'BankingProtocol -> BankingProtocol : TppConsentSession.psuConsentSession()\n:PsuConsentSession
    return RedirectException(TppRedirectURL<auth-id,rediredCode>, )
    return 303_SeeOther(PsuConsentSession,\nConsentAuthorisationApi\n.auth<redirectCode>)
    FinTechApi -> FinTechApi : finTechConsentSessionCookie(PsuConsentSession,\nfinTechConsentSessionState):FinTechConsentSessionCookie
    return 302_Redirect[ConsentAuthorisationApi.auth<redirectCode,\nfinTechConsentSessionState>,\nFinTechConsentSessionCookie]()
else TppConsentSession.consentPresent()
    autonumber 71 1 "<b><color blue>[InitConsent-000]"
    activate BankingProtocol
    BankingProtocol -> AspspBankingApi ++ : listOfTransactions[UserAgentContext,\nTppContext](AisConsent) 
    return 200_OK[](Transactions)
    BankingProtocol --> TppBankingApi ++: 200_OK[](Transactions)
    deactivate BankingProtocol
    TppBankingApi --> FinTechApi ++ : 200_OK[](Transactions)
    deactivate TppBankingApi
    FinTechApi --> FinTechUI : 200_OK[FintechLoginSessionCookie](Transactions)
    deactivate FinTechApi
    return displayListOfTransactions(Transactions)
end
@enduml
