@startuml PsuAuthorizeRedirectConsent
title PsuAuthorizeRedirectConsent
autonumber "<b><color blue>[00]"
actor psu

box "PsuUserAgent" #LightGray
    participant "FinTechUI" as FinTechUI
    participant "ConsentAuthorisationUI" as ConsentAuthorisationUI
    participant "OnlineBankingUI" as OnlineBankingUI
end box
box "FinTechDC" #DarkSeaGreen
    participant "FinTechApi" as FinTechApi
end box
box "TppDC" #LightGray
    participant "TppBankingApi" as TppBankingApi
    participant "TppBankSearchApi" as TppBankSearchApi
    participant "ConsentAuthorisationApi" as ConsentAuthorisationApi

    participant "RedirectSessionStoreApi" as RedirectSessionStoreApi
    participant "BankingProtocol" as BankingProtocol
end box
box "AspspDC" #LightSkyBlue
	participant "AspspBankingApi" as AspspBankingApi
    participant "OnlineBankingApi" as OnlineBankingApi
end box

== Initiate consent upon PSU transaction display request : call[header](body)<params> return code[header](body) ==

FinTechUI -> ConsentAuthorisationApi ++ : GET:ConsentAuthorisationApi.redirectAuthEntryPoint[UserAgentContext]()<redirectCode>
ConsentAuthorisationApi -> RedirectSessionStoreApi ++ : redirectSession(redirectCode)
RedirectSessionStoreApi -> RedirectSessionStoreApi : loadDeryptDeleteRedirectSession\n(redirectCode):TppConsentSession
return TppConsentSession
ConsentAuthorisationApi -> ConsentAuthorisationUI ++ : 200_OK[Psu2TppConsentSessionCookie,\nConsentAuthorisationUI.infoPanel](TppConsentSession)
deactivate ConsentAuthorisationApi
ConsentAuthorisationUI --> psu : displayTpp2AspspRedirectionInfoPanel()
deactivate ConsentAuthorisationUI
psu -> ConsentAuthorisationUI ++ : confirmRedirect()
ConsentAuthorisationUI -> ConsentAuthorisationApi ++ : GET:ConsentAuthorisationApi.confirmRedirect[Psu2TppConsentSessionCookie]()<consentSessionState>
deactivate ConsentAuthorisationUI
ConsentAuthorisationApi --> OnlineBankingUI ++ : redirect302[OnlineBankingApi.redirectEntryPoint]\n()<consentId, authorizationId>
group Psu2AspspConsentSession
    OnlineBankingUI -> OnlineBankingApi ++ : redirectEntryPoint[]()<consentId, authorizationId>
    return redirect302[Psu2AspspConsentSession, OnlineBankingUI.loginScreen, Psu2AspspConsentSessionCookie]()<consentId, authorizationId>
    OnlineBankingUI --> psu : displayLoginScreen()
    deactivate OnlineBankingUI
    psu -> OnlineBankingUI ++ : loginData(PsuAuthData)
    OnlineBankingUI -> OnlineBankingApi ++ : POST:login[Psu2AspspConsentSessionCookie](PsuAuthData)<consentId, authorizationId> 
    return 200_OK[Psu2AspspConsentSessionCookie,OnlineBankingApi.selectScaMethod](Psu2AspspConsentSession,ScaMethods)
    return displayAisConsentAndScaMethods(ScaMethods)
    psu -> OnlineBankingUI ++ : selectScaMethod(selectedScaMethod)
    OnlineBankingUI -> OnlineBankingApi ++ : GET:selectScaMethod[Psu2AspspConsentSessionCookie](selectedScaMethod)<consentId, authorizationId> 
    return 200_OK[Psu2AspspConsentSessionCookie,OnlineBankingApi.enterOTP](Psu2AspspConsentSession,ScaData)
    return displayAisConsentAndOTPScreen\n(Psu2AspspConsentSession.otpMetaData)
    psu -> OnlineBankingUI ++ : enterOTP(otp)
    OnlineBankingUI -> OnlineBankingApi ++ : authorizeConsent[Psu2AspspConsentSessionCookie](TAN)<consentId, authorizationId> 
    return 200_OK[Psu2AspspConsentSessionCookie,\nOnlineBankingUI.infoPanel](Psu2AspspConsentSession)
    OnlineBankingUI --> psu : displayAspsp2TppRedirectionInfoPanel()
    deactivate OnlineBankingUI
    psu -> OnlineBankingUI ++ : confirmRedirect()
    OnlineBankingUI -> OnlineBankingApi ++ : GET:OnlineBankingApi.confirmRedirect[Psu2AspspConsentSessionCookie]()<consentId, authorizationId>
    deactivate OnlineBankingUI
    OnlineBankingApi --> ConsentAuthorisationUI ++ : redirect302[OnlineBankingApi.TPP-Redirect-URI]\n()<consentId, authorizationId>
    deactivate OnlineBankingApi
end
activate ConsentAuthorisationUI
ConsentAuthorisationUI -> ConsentAuthorisationApi ++ : GET:TPP-Redirect-URI[Psu2TppConsentSessionCookie]()<consentId, authorizationId>
ConsentAuthorisationApi -> BankingProtocol ++ : getConsentStatus(consentId)
BankingProtocol -> OnlineBankingApi ++ : getConsentStatus[consentId, TppContext]()
return TppConsentSession
BankingProtocol -> BankingProtocol : TppConsentSession\n.tppConsentSession():TppConsentSession
return 200_OK(TppConsentSession)
ConsentAuthorisationApi -> RedirectSessionStoreApi ++ : redirectSession(TppConsentSession, exp)
RedirectSessionStoreApi -> RedirectSessionStoreApi : createEncryptStoreRedirectSession\n(TppConsentSession):redirectCode
return 200_OK[](redirectCode)<>
return redirect302[Psu2TppConsentSessionCookie=null,\nFinTechApi.FinTech-Redirect-URI<redirectCode>]()
@enduml
