version: "3.3"

networks:
  opba-net:

services:
  postgres:
    image: "postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=open_banking
    ports:
      #HOST:CONTAINER
      - "5432:5432"
    volumes:
      - ./opba-db/src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./fintech-examples/fintech-db-schema/src/main/resources/init.sql:/docker-entrypoint-initdb.d/fintech-init.sql
    networks:
      - opba-net

