@startuml
skinparam nodesep 10
skinparam ranksep 10
skinparam swimlane {
  BorderThickness 2
  TitleFontColor black
  TitleFontSize 20
  width 30
}

|FinTech with OpenBankingGw API|
:{{
database "Dynamic KB\n(i.e. consent id)" as DKB
component "FinTech KB adapter" as FKBA
DKB ==> FKBA
}};
-> Read transactions - call\n**GET /transactions/{bankId}** with consent ID;
|#AntiqueWhite|TPP with OpenBankingGw Impl|
note right
  For <b>MVP0</b>:
  - Needs Consent? Simply read from bank
  profile definition table
  - Consent valid? Stubbed to assume is always valid
  For <b>MVP1</b>:
  Answers to both questions are handled by rule engine or BPMN flow.
end note
if (Needs Consent?) then (YES)
if (Consent valid?) then (YES)
|FinTech with OpenBankingGw API|
|#AntiqueWhite|TPP with OpenBankingGw Impl|
else (NO)
if (Ask for consent automatically parameter missing?) then (ABSENT)
|FinTech with OpenBankingGw API|
:Notification that consent is missing;
stop
else (PRESENT)
|#AntiqueWhite|TPP with OpenBankingGw Impl|
' Initiate consent flow
|#AntiqueWhite|TPP with OpenBankingGw Impl|
:{{
database "Static KB\n(i.e. bank profile)" as SKB
database "Dynamic KB\n(i.e. FinTech\nphysical address)" as DKB
component "<size:30><&spreadsheet></size>Request context knowledge" as knowledge
DKB ==> knowledge
SKB ==> knowledge
}};
:{{
component "<size:30><&cog></size> Request validation engine\n(mock that validates if\nall params are present)" as mockEngine
component "<size:30><&fork></size>ASPSP mock endpoints with\nrequest definition" as ASPSPMock
mockEngine <=left=> ASPSPMock : Mock requests
}};
|BPMN Engine inside TPP|
:{{
skinparam nodesep 10
skinparam ranksep 10
header
<font color=red>Same flow as below (Consent creation)</font>
endheader
AIS -> "(MOCK) ASPSP" ++ : Consent creation request
return Consent creation response
AIS -> "(MOCK) ASPSP" ++ : Consent status request
return Consent status response
}};
|TPP with OpenBankingGw Impl|
if (<size:14>Not all required parameters</size>\n<size:14>are present?</size>) then (YES)
|FinTech with OpenBankingGw API|
:Handle not all parameters\nare available for AIS consent creation;
stop
else (NO - ALL PRESENT)
|TPP with OpenBankingGw Impl|
:{{
component "<size:30><&cog></size>Request performing engine (<b><&cog>RPE</b>)" as engine
}};
endif
|#AntiqueWhite|BPMN Engine inside TPP|
:{{
skinparam nodesep 10
skinparam ranksep 10
header
<font color=red>Consent creation</font>
endheader
AIS -> ASPSP ++ : Create consent request
return Create consent response
AIS -> PSU : Authorize consent
loop SCA Authorization
ASPSP -> PSU : SCA challenge
PSU -> ASPSP : Challenge result
end
}};
-> Call sequence to declare consent on behalf of <b>TPP</b>;
|ASPSP|
:Create consent;
note right
  Generated by <&cog>RPE
end note
:Authorize consent;
note right
  Generated by <&cog>RPE
end note
|PSU|
:Complete SCA challenge;
|ASPSP|
:Confirmed;
note right
  Generated by <&cog>RPE
end note
|TPP with OpenBankingGw Impl|
:PSU has confirmed AIS consent;
endif
endif
endif
|#AntiqueWhite|TPP with OpenBankingGw Impl|
:Check consent is valid;
:{{
database "Static KB\n(i.e. bank profile)" as SKB
database "Dynamic KB\n(i.e. Client billing address)" as DKB
component "<size:30><&spreadsheet></size>Request context knowledge" as knowledge
DKB ==> knowledge
SKB ==> knowledge
}};
:{{
component "<size:30><&cog></size> Request validation engine\n(mock that validates if\nall params are present)" as mockEngine
component "<size:30><&fork></size>ASPSP mock endpoints with\nrequest definition" as ASPSPMock
mockEngine <=left=> ASPSPMock : Mock requests
}};
|BPMN Engine inside TPP|
:{{
skinparam nodesep 10
skinparam ranksep 10
header
<font color=red>Same flow as below (Transaction list)</font>
endheader
AIS -> "(MOCK) ASPSP" ++ : List transactions
return Transaction list
}};
|TPP with OpenBankingGw Impl|
if (<size:14>Not all required parameters</size>\n<size:14>are present?</size>) then (YES)
|FinTech with OpenBankingGw API|
:Handle not all parameters are\navailable to list transactions;
stop
else (NO - ALL PRESENT)
|TPP with OpenBankingGw Impl|
:{{
component "<size:30><&cog></size>Request performing engine (<b><&cog>RPE</b>)" as engine
}};
endif
|#AntiqueWhite|BPMN Engine inside TPP|
:{{
skinparam nodesep 10
skinparam ranksep 10
header
<font color=red>Transaction list</font>
endheader
AIS -> ASPSP ++ : List transactions
return Transaction list
}};
-> Call sequence to list transactions on behalf of <b>TPP</b>;
|ASPSP|
|ASPSP|
:List transactions with consent ID;
note right
  Generated by <&cog>RPE
end note
|TPP with OpenBankingGw Impl|
:List of transactions;
|FinTech with OpenBankingGw API|
:List of transactions;
stop
@enduml