version: "3.4"

networks:
  opba-net:

x-sandbox-hosts: &sandbox-hosts
  COMMON_APPS_LOCAL_ASPSPPROFILE_HOST: x2sa-sandbox-aspspprofile
  COMMON_APPS_LOCAL_ASPSPPROFILE_PORT: 8080
  COMMON_APPS_LOCAL_CERTGENERATOR_HOST: x2sa-sandbox-certgenerator
  COMMON_APPS_LOCAL_CERTGENERATOR_PORT: 8092
  COMMON_APPS_LOCAL_CONSENTMGMT_HOST: x2sa-sandbox-consentmgmt
  COMMON_APPS_LOCAL_CONSENTMGMT_PORT: 8080
  COMMON_APPS_LOCAL_LEDGERSAPP_HOST: x2sa-sandbox-ledgersapp
  COMMON_APPS_LOCAL_LEDGERSAPP_PORT: 8088
  COMMON_APPS_LOCAL_LEDGERSGATEWAY_HOST: x2sa-sandbox-ledgersgateway
  COMMON_APPS_LOCAL_LEDGERSGATEWAY_PORT: 8089
  COMMON_APPS_LOCAL_ONLINEBANKING_HOST: x2sa-sandbox-onlinebanking
  COMMON_APPS_LOCAL_ONLINEBANKING_PORT: 8090
  COMMON_APPS_LOCAL_TPPREST_HOST: x2sa-sandbox-tpprest
  COMMON_APPS_LOCAL_TPPREST_PORT: 8093
  COMMON_APPS_LOCAL_ONLINEBANKINGUI_HOST: localhost # This container is launched in the host network
  COMMON_APPS_LOCAL_ONLINEBANKINGUI_PORT: 4400 # this port seem to be used in lot of places, hard to change

services:
  opba-postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=open_banking
    ports:
      #HOST:CONTAINER
      - 15432:5432
    volumes:
      - ../../opba-db/src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - opba-net

  opba-banking-gateway:
    image: open-banking-gateway
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://opba-postgres:5432/open_banking?currentSchema=banking_protocol
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=docker
      - PKCS12_KEYSTORE=/pkcs12/sample-qwac.keystore
      - SPRING_PROFILES_ACTIVE=${OPBA_PROFILES},technical-ui
      - PROTOCOL_GATEWAY_BASE_URL=http://localhost:18085
      - EMBEDDED_UI_BASE_URL=http://localhost:5500
      - SPRING_LIQUIBASE_PARAMETERS_ADORSYS_SANDBOX_URL=http://x2sa-sandbox-ledgersgateway:8089
      - FACADE_ENCRYPTION_KEYSETPATH=/keysetpath/example-keyset.json
    ports:
      - 18085:8085
    volumes:
      - ../../opba-protocols/xs2a-protocol/src/main/resources/:/pkcs12/
      - ../../opba-banking-protocol-facade/src/main/resources/:/keysetpath/
    depends_on:
      - opba-postgres
    networks:
      - opba-net

  opba-technical-ui:
    image: technical-tpp-ui
    environment:
      TPP_BANKING_UI_HOST_AND_PORT: localhost:4400
      TECHNICAL_UI_HOST_AND_PORT: localhost:5500
      EMBEDDED_SERVER_URL: http://opba-banking-gateway:8085
    restart: on-failure
    volumes:
      - ../../technical-embedded-ui/tpp-ui:/usr/src/app
    ports:
      - 5500:5500
    depends_on:
      - opba-banking-gateway
      - x2sa-sandbox-onlinebankingui
    networks:
      - opba-net

#
#
#          ========================= XS2A-SANDBOX ==================================
#
#
  xs2a-sandbox-postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=sandbox_apps
    ports:
      #HOST:CONTAINER
      - 25432:5432
    volumes:
      - ../../opba-protocols/sandboxes/xs2a-sandbox/src/main/resources/sandbox/prepare-postgres.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - opba-net

  x2sa-sandbox-onlinebankingui:
    image: adorsys/xs2a-online-banking-ui:2.9
    environment:
      ONLINE_BANKING_SERVER_URL: http://x2sa-sandbox-onlinebanking:8090
    ports:
      - 4400:4400
    depends_on:
      - x2sa-sandbox-onlinebanking
    networks:
      - opba-net

  x2sa-sandbox-tpprest:
    image: adorsys/xs2a-tpp-rest-server:2.9
    environment:
      <<: *sandbox-hosts
      SPRING_PROFILES_INCLUDE: test-db-local-postgres,test-common,test-tpp-rest
      SPRING_CONFIG_LOCATION: classpath:/,/configs/application-test-common.yml,/configs/application-test-db-local-postgres.yml,/configs/application-test-tpp-rest.yml
      DB_HOST_AND_PORT: xs2a-sandbox-postgres:5432
    ports:
      - 20016:8093
    depends_on:
      - opba-banking-gateway
      - x2sa-sandbox-onlinebankingui
      - x2sa-sandbox-ledgersapp
    volumes:
      - ../../opba-protocols/sandboxes/xs2a-sandbox/src/main/resources/sandbox:/configs
    networks:
      - opba-net

  x2sa-sandbox-onlinebanking:
    image: adorsys/xs2a-online-banking:2.9
    environment:
      <<: *sandbox-hosts
      SPRING_PROFILES_INCLUDE: test-db-local-postgres,test-common,test-online-banking
      SPRING_CONFIG_LOCATION: classpath:/,/configs/application-test-common.yml,/configs/application-test-db-local-postgres.yml,/configs/application-test-online-banking.yml
      DB_HOST_AND_PORT: xs2a-sandbox-postgres:5432
    ports:
      - 20015:8090
    depends_on:
      - xs2a-sandbox-postgres
      - x2sa-sandbox-ledgersapp
    volumes:
      - ../../opba-protocols/sandboxes/xs2a-sandbox/src/main/resources/sandbox:/configs
    networks:
      - opba-net

  x2sa-sandbox-ledgersgateway:
    image: adorsys/xs2a-connector-examples:5.10
    environment:
      <<: *sandbox-hosts
      SPRING_PROFILES_INCLUDE: test-db-local-postgres,test-common,test-ledgeres-gateway,postgres,mock-qwac,remote
      SPRING_CONFIG_LOCATION: classpath:/,/configs/application-test-common.yml,/configs/application-test-db-local-postgres.yml,/configs/application-test-ledgers-gateway.yml
      DB_HOST_AND_PORT: xs2a-sandbox-postgres:5432
    ports:
      - 20014:8089
    depends_on:
      - x2sa-sandbox-onlinebankingui
      - x2sa-sandbox-ledgersapp
    volumes:
      - ../../opba-protocols/sandboxes/xs2a-sandbox/src/main/resources/sandbox:/configs
    networks:
      - opba-net

  x2sa-sandbox-ledgersapp:
    image: adorsys/ledgers:2.8
    environment:
      <<: *sandbox-hosts
      SPRING_PROFILES_INCLUDE: test-db-local-postgres,test-common,test-ledgeres-app,develop,sandbox
      SPRING_CONFIG_LOCATION: classpath:/,/configs/application-test-common.yml,/configs/application-test-db-local-postgres.yml,/configs/application-test-ledgers-app.yml
      DB_HOST_AND_PORT: xs2a-sandbox-postgres:5432
    ports:
      - 20013:8088
    depends_on:
      - xs2a-sandbox-postgres
    volumes:
      - ../../opba-protocols/sandboxes/xs2a-sandbox/src/main/resources/sandbox:/configs
    networks:
      - opba-net

  x2sa-sandbox-consentmgmt:
    image: adorsys/xs2a-consent-management:5.10
    environment:
      <<: *sandbox-hosts
      SPRING_PROFILES_INCLUDE: test-db-local-postgres,test-common,test-consent-mgmt
      SPRING_CONFIG_LOCATION: classpath:/,/configs/application-test-common.yml,/configs/application-test-db-local-postgres.yml,/configs/application-test-consent-mgmt.yml
      DB_HOST_AND_PORT: xs2a-sandbox-postgres:5432
    ports:
      - 20012:8080
    depends_on:
      - xs2a-sandbox-postgres
    volumes:
      - ../../opba-protocols/sandboxes/xs2a-sandbox/src/main/resources/sandbox:/configs
    networks:
      - opba-net

  x2sa-sandbox-certgenerator:
    image: adorsys/xs2a-certificate-generator:2.9
    environment:
      <<: *sandbox-hosts
      SPRING_PROFILES_INCLUDE: test-db-local-postgres,test-common,test-cert-generator
      SPRING_CONFIG_LOCATION: classpath:/,/configs/application-test-common.yml,/configs/application-test-db-local-postgres.yml,/configs/application-test-cert-generator.yml
      DB_HOST_AND_PORT: xs2a-sandbox-postgres:5432
    ports:
      - 20011:8092
    depends_on:
      - xs2a-sandbox-postgres
    volumes:
      - ../../opba-protocols/sandboxes/xs2a-sandbox/src/main/resources/sandbox:/configs
    networks:
      - opba-net

  x2sa-sandbox-aspspprofile:
    image: adorsys/xs2a-aspsp-profile:5.10
    environment:
      <<: *sandbox-hosts
      PRIMARY_PROFILE: /configs/application-test-aspsp-profile.yml
      SPRING_PROFILES_INCLUDE: test-db-local-postgres,test-common,test-aspsp-profile,debug_mode
      SPRING_CONFIG_LOCATION: classpath:/,/configs/application-test-common.yml,/configs/application-test-db-local-postgres.yml,/configs/application-test-aspsp-profile.yml
      DB_HOST_AND_PORT: xs2a-sandbox-postgres:5432
    ports:
      - 20010:8080
    depends_on:
      - xs2a-sandbox-postgres
    volumes:
      - ../../opba-protocols/sandboxes/xs2a-sandbox/src/main/resources/sandbox:/configs
    networks:
      - opba-net
