openapi: 3.0.1
info:
  version: "1.0.0"
  title: Open Banking Gateway Banking API
  description: >-
    This API provides FinTech possibilities to perform use-cases specific calls to the bank of PSU.
externalDocs:
  url: "https://adorsys.github.com/open-banking-gateway"


paths:

  /v1/ais/accounts:
    get:
      summary: Provides list of available accounts
      tags:
        - Account information service (AIS)
      description: >-
        Read the identifiers of the available payment accounts.

        It is assumed that a consent of the PSU to this access is already given and stored on the TPP system.
        The addressed list of accounts depends then on the PSU and Consent information, stored respectively the OAuth2 access token.

        Returns all identifiers of the accounts, to which an account access has been granted to by the PSU.
        In addition, relevant information about the accounts and hyperlinks to corresponding account
        information resources are provided if a related consent has been already granted.

      parameters:
        #header
        #common header parameter
        - $ref: "#/components/parameters/X-Request-ID"
      security:
        - BearerAuthOAuth: []
      responses:
        '200':
          $ref: "#/components/responses/200_AccountList"
        '303':
          $ref: '#/components/responses/303_REDIRECT'
        '401':
          description: Unauthorised

  /v1/ais/accounts/{account-id}/transactions:
    get:
      summary: Provides list of transactions by given account
      tags:
        - Account information service (AIS)
      description: >-
        This operation shows how to override the global security defined above,
        as we want to open it up for all users.
      parameters:
        #path
        - $ref: "#/components/parameters/account-id"
          #header
          #common header parameter
        - $ref: "#/components/parameters/X-Request-ID"
      security:
        - BearerAuthOAuth: []
      responses:
        '200':
          description: OK
        '303':
          description: Authorisation session mandated
        '401':
          description: Unauthorised

components:
  headers:
    X-Request-ID:
      required: true
      description: |
        Unique ID that identifies this request through common workflow.
        Shall be contained in HTTP Response as well.
      example: "99391c7e-ad88-49ec-a2ad-99ddcb1f7721"
      schema:
        type: string
        format: uuid

  parameters:
    X-Request-ID:
      name: X-Request-ID
      in: header
      required: true
      description: |
        Unique ID that identifies this request through common workflow.
        Shall be contained in HTTP Response as well.
      example: "99391c7e-ad88-49ec-a2ad-99ddcb1f7721"
      schema:
        type: string
        format: uuid

    account-id:
      name: account-id
      in: path
      required: true
      schema:
        type: string
  responses:
    303_REDIRECT:
      description: |
        Authorisation session mandated. Agent shall redirect the user to the Authorisation URI provided in response.
      headers:
        X-Request-ID:
          $ref: "#/components/headers/X-Request-ID"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/AuthChallenge"

    200_AccountList:
      description: OK
      headers:
        X-Request-ID:
          $ref: "#/components/headers/X-Request-ID"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/accountList"

  schemas:
    AuthChallenge:
      description: |
        The PSU shall perform the authorisation procedures at ASPSP through the interface provided by the given link. Additional get parameters 'Agent-Callback-OK' and 'Agent-Callback-NOK' may be added to the link by the agent to get notified about the procedure end.
      type: object
      properties:
        web:
          $ref: "#/components/schemas/hrefType"


    accountDetails:
      description: |
        The ASPSP shall give at least one of the account reference identifiers:
          - iban
          - bban
          - pan
          - maskedPan
          - msisdn
        If the account is a multicurrency account currency code in "currency" is set to "XXX".
      type: object
      required:
        - currency
      properties:
        resourceId:
          description: This shall be filled, if addressable resource are created by the ASPSP on the /accounts or /card-accounts endpoint.
          type: string
        iban:
          $ref: "#/components/schemas/iban"
        bban:
          $ref: "#/components/schemas/bban"
        pan:
          $ref: "#/components/schemas/pan"
        maskedPan:
          $ref: "#/components/schemas/maskedPan"
        msisdn:
          $ref: "#/components/schemas/msisdn"
        currency:
          $ref: "#/components/schemas/currencyCode"
        name:
          description: Name of the account given by the bank or the PSU in online-banking.
          type: string
          maxLength: 35
        product:
          description: Product name of the bank for this account, proprietary definition.
          type: string
          maxLength: 35
        cashAccountType:
          $ref: "#/components/schemas/cashAccountType"
        status:
          $ref: "#/components/schemas/accountStatus"
        bic:
          $ref: "#/components/schemas/bicfi"
        linkedAccounts:
          description: Case of a set of pending card transactions, the APSP will provide the relevant cash account the card is set up on.
          type: string
          maxLength: 70
        usage:
          description: |
            Specifies the usage of the account:
              * PRIV: private personal account
              * ORGA: professional account
          type: string
          maxLength: 4
          enum:
            - "PRIV"
            - "ORGA"
        details:
          description: |
            Specifications that might be provided by the ASPSP:
              - characteristics of the account
              - characteristics of the relevant card
          type: string
          maxLength: 140
        _links:
          $ref: "#/components/schemas/linksAccountDetails"
        ownerName:
          description: Name of the legal account owner. If there is more than one owner, then e.g. two names might be noted here.
          type: string
          maxLength: 70
        ownerAddress:
          $ref: "#/components/schemas/address"

    accountList:
      description: |
        List of accounts with details.
      type: object
      required:
        - accounts
      properties:
        accounts:
          type: array
          items:
            $ref: "#/components/schemas/accountDetails"

    accountStatus:
      description: |
        Account status. The value is one of the following:
          - "enabled": account is available
          - "deleted": account is terminated
          - "blocked": account is blocked e.g. for legal reasons
        If this field is not used, than the account is available in the sense of this specification.
      type: string
      enum:
        - "enabled"
        - "deleted"
        - "blocked"

    address:
      type: object
      required:
        - country
      properties:
        streetName:
          type: string
          maxLength: 70
        buildingNumber:
          type: string
        townName:
          type: string
        postCode:
          type: string
        country:
          $ref: "#/components/schemas/countryCode"
      example:
        {
          street: "rue blue",
          buildingnNumber: "89",
          city: "Paris",
          postalCode: "75000",
          country: "FR"
        }

    bban:
      description: |
        Basic Bank Account Number (BBAN) Identifier.

        This data element can be used in the body of the Consent request.
          Message for retrieving Account access Consent from this Account. This
          data elements is used for payment Accounts which have no IBAN.
          ISO20022: Basic Bank Account Number (BBAN).

          Identifier used nationally by financial institutions, i.e., in individual countries,
          generally as part of a National Account Numbering Scheme(s),
          which uniquely identifies the account of a customer.
      type: string
      pattern: "[a-zA-Z0-9]{1,30}"
      example: "BARC12345612345678"



    bicfi:
      description: |
        BICFI
      type: string
      pattern: "[A-Z]{6,6}[A-Z2-9][A-NP-Z0-9]([A-Z0-9]{3,3}){0,1}"
      example: "AAAADEBBXXX"

    cashAccountType:
      description: |
        ExternalCashAccountType1Code from ISO 20022.
      type: string


    countryCode:
      description: ISO 3166 ALPHA2 country code.
      type: string
      pattern: "[A-Z]{2}"
      example: "SE"


    currencyCode:
      description: |
        ISO 4217 Alpha 3 currency code.
      type: string
      pattern: "[A-Z]{3}"
      example: "EUR"

    hrefType:
      description: Link to a resource.
      type: object
      properties:
        href:
          $ref: "#/components/schemas/hrefEntry"

    hrefEntry:
      description: Link to a resource.
      type: string
      example: "https://www.example.com/path/resource?parameter=value"

    iban:
      type: string
      description: International bank account number ISO 31616.
      pattern: "[A-Z]{2,2}[0-9]{2,2}[a-zA-Z0-9]{1,30}"
      example: "FR7612345987650123456789014"

    linksAccountDetails:
      description: |
        Links to the account, which can be directly used for retrieving account information from this dedicated account.

        Links to "balances" and/or "transactions"

        These links are only supported, when the corresponding consent has been already granted.
      type: object
      properties:
        balances:
          $ref: "#/components/schemas/hrefType"
        transactions:
          $ref: "#/components/schemas/hrefType"

    maskedPan:
      description: |
        Masked Primary Account Number.
      type: string
      maxLength: 35
      example: "123456xxxxxx1234"

    msisdn:
      type: string
      maxLength: 35
      description: Mobile phone number.
      example: "+49 170 1234567"

    pan:
      description: |
        Primary Account Number according to ISO/IEC 7812.
      type: string
      maxLength: 35
      #According to ISO the following should be valid.
      #maxLength: 19
      #minLength: 8
      #pattern: "[0-9]{8,19}"
      example: "5409050000000000"



  securitySchemes:
    BearerAuthOAuth:
      description: |
        Bearer Token.
      type: http
      scheme: bearer
    accessCode:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: 'http://example.com/oauth/auth'
          tokenUrl: 'http://example.com/oauth/token'
          scopes:
            write: allows modifying resources
            read: allows reading resources
