### GET request with a header
GET http://172.20.0.3:8080/api/v1/about/user
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMzAyMjQ4NWYwNGIwN2U3NWU0MzE1NGE0ZDI1MTIyN2ZkZWEyZDFiYjNmZTNhNGYzY2I4MWMxYWZlZGI5NjlkZmI3MGE2ZGM4ZGI0MjE3MzgiLCJpYXQiOjE2MDEwMjQwMTksIm5iZiI6MTYwMTAyNDAxOSwiZXhwIjoxNjMyNTYwMDE5LCJzdWIiOiIxIiwic2NvcGVzIjpbXX0.aK2iYtAY7xL2NFG4k_aXl46DsN1aX-4gN7xT2huE-BGv0Sn-YxpoNtVUElGFLCBHgUhSUaZLVQtx94Q4NW1rTIg8Fqrl8QjzqCoO8xWQxygmxVhfuDrLISe91DiIRo7Aigt-1G0UyRnvV8L12tOHsumkeS1LSr6k_StSPi3yDDWnX4AFv1x7p2ZXE5m-zCnVE1YlvrkuVep2312pe97Ag6ZhKS6HqCH1pJC0SjQkIE3tsTGGOEW9fHFIToQaPtli4I_MrkusfRCpeQSl5Jyjr1tiXErdekKri2HC27ygQ8hZtg0LhccpVdwpz0gGclsADyMxJnIqfuf-ws2iwUbD6ASFKoFzLOr6Src6e2p3Qs_H-g0JB_sYRg9p9lqYiXZR1AURrDFWJVMGKTrKiv5ZikDfqWOqdFDhEj9uN3hM-hhb_F9zSBAxUTnIuufJjJr_zQgsIh4xUuWja43S8clJN9L4Alv0KtNkOhfD8QNtPp1NLSvzOZpJCRXDMdvfCk-0tnEkjJNcENuhaTmlm9tWEmV-CqgjhbN0GKWi1kQmY5jljqh2tY89ooOnOAlnmhIfK9RxUQOQN7aCAPPbGoN64KjbV2JEHzXac2CvWnibqx2P9PQI0Ko7Q-VSXyTK6sK439XQCgm4mWzDNvi0KmAThikeR6KQ7SLxZ5rcqOEhym8