@startuml

autonumber "<b><color blue>[00]"
actor psu

box "PsuUserAgent" #LightGray
    participant "FinTechUI" as FinTechUI
    participant "PsuTppConsentSessionUI" as TppConsentUI
    participant "PsuAspspConsentSessionUI" as AspspConsentUI
end box
box "FinTechDC" #DarkSeaGreen
    participant "FinTechApi" as FinTechAPI
end box
box "TppDC" #LightGray
    participant "TppBankingApi" as TPPBankingAPI
    participant "TppBankSearchAPI" as BankList
    participant "TppConsentSessionApi" as ConsentAPI
    participant "TppConsentSessionStoreAPI" as ConsentStore
    participant "BankingProtocolSelector" as ProtocolSelector
    participant "BankingProtocol" as BankingProtocol
    participant ConsentDB
end box
box "AspspDC" #LightSkyBlue
    participant "AspspConsentSessionApi" as ASPSP
end box

== PSU establishes a session with the FinTech API ==
psu -> FinTechUI ++ : Load FinTech Application
FinTechUI -> FinTechAPI ++ : login(psu-auth@fintech)
return storeSessionCookie[PsuFinTechSessionCookie]
note right
    terminology -> call[header](body)
    PsuFinTechSessionCookie = Psu Session Cookie
    psu-auth@fintech = Data used to authenticate
    the psu at the fintech interface
end note
return Display use case "Bank Selection"

@enduml