@startuml

autonumber "<b><color blue>[00]"
actor psu

box "PsuUserAgent" #LightGray
    participant "FinTechUI" as FinTechUI
    participant "PsuTppConsentSessionUI" as TppConsentUI
    participant "PsuAspspConsentSessionUI" as AspspConsentUI
end box
box "FinTechDC" #DarkSeaGreen
    participant "FinTechApi" as FinTechAPI
end box
box "TppDC" #LightGray
    participant "TppBankingApi" as TPPBankingAPI
    participant "TppBankSearchAPI" as BankList
    participant "TppConsentSessionApi" as ConsentAPI
    participant "TppConsentSessionStoreAPI" as ConsentStore
    participant "BankingProtocolSelector" as ProtocolSelector
    participant "BankingProtocol" as BankingProtocol
    participant ConsentDB
end box
box "AspspDC" #LightSkyBlue
    participant "AspspConsentSessionApi" as ASPSP
end box

== PSU searches and selects a bank ==
psu -> FinTechUI ++ : Select UC "Bank Selection"
note right
    whithout a bank selected we can not 
    know what services to offer to the psu
end note
return Display bank search screen

psu -> FinTechUI ++ : incrementalBankSearch(keyword)
FinTechUI -> FinTechAPI ++ : incrementalBankSearch(keyword)
FinTechAPI -> BankList ++ : incrementalBankSearch(keyword)
return bankList
return bankList
return Display bank list

psu -> FinTechUI ++ : selectBank
FinTechUI -> FinTechAPI ++ : selectBank[...](bankId)
FinTechAPI -> TPPBankingAPI ++ : selectBank[...](bankId)
TPPBankingAPI -> ProtocolSelector ++: selectBankingProtocol(bankId)
return BankingProtocol
TPPBankingAPI -> BankingProtocol ++ : getBankProfile(bankId)
BankingProtocol -> BankList ++ : getBankProfile(bankId)
return bankProfile
return bankProfile
return bankProfile
return bankProfile
return Display use case

@enduml