@startuml

autonumber "<b><color blue>[00]"
actor psu

box "User Agent" #LightGray
    participant "FinTech UI" as FinTechUI
    participant "TPP PSU\nConsentUI" as TppConsentUI
    participant "ASPSP\nConsentUI" as AspspConsentUI
end box
participant "Fintech API" as FinTechAPI
box "Banking Gateway (TPP)" #LightGray
    participant "TPP Banking API" as TPPBankingAPI
    participant "Bank Search API" as BankList
    participant "TPP Consent\nSession API" as ConsentAPI
    participant "TPP Consent\nSession Store API" as ConsentStore
    participant "Banking Protocol\nSelector" as ProtocolSelector
    participant "Banking Protocol" as BankingProtocol
    participant ConsentDB
end box
participant "ASPSP (Bank)" as ASPSP

== PSU searches and selects a bank ==
psu -> FinTechUI ++ : Select UC "Bank Selection"
note right
    whithout a bank selected we can not 
    know what services to offer to the psu
end note
return Display bank search screen

psu -> FinTechUI ++ : incrementalBankSearch(keyword)
FinTechUI -> FinTechAPI ++ : incrementalBankSearch(keyword)
FinTechAPI -> BankList ++ : incrementalBankSearch(keyword)
return bankList
return bankList
return Display bank list

psu -> FinTechUI ++ : selectBank
FinTechUI -> FinTechAPI ++ : selectBank[...](bankId)
FinTechAPI -> TPPBankingAPI ++ : selectBank[...](bankId)
TPPBankingAPI -> ProtocolSelector ++: selectBankingProtocol(bankId)
return BankingProtocol
TPPBankingAPI -> BankingProtocol ++ : getBankProfile(bankId)
BankingProtocol -> BankList ++ : getBankProfile(bankId)
return bankProfile
return bankProfile
return bankProfile
return bankProfile
return Display use case

@enduml