# Alias xs2a at 8089 on host
server:
  port: ${common.apps.local.ledgersgateway.port}

spring:
  profiles:
    # FIXME: Maybe mock-qwac is not good idea
    active: postgres,mock-qwac,remote

aspsp-profile:
  baseurl: ${common.apps.mapping.aspsp}/api/v1
consent-service:
  baseurl: ${common.apps.mapping.consentmgmt}/api/v1
ledgers:
  url: ${common.apps.mapping.ledgersapp}
cms:
  url: ${common.apps.mapping.consentmgmt}
online-banking:
  url: ${common.apps.mapping.onlinebanking}/api/v1/consents/confirm/{userLogin}/{consentId}/{authorizationId}/{tan}

# To verify:
skip_ssl_certificate_verification: true

qwac-certificate-mock: -----BEGIN CERTIFICATE-----MIIFMTCCAxmgAwIBAgIEdoWFyDANBgkqhkiG9w0BAQsFADB4MQswCQYDVQQGEwJERTEQMA4GA1UECAwHQkFWQVJJQTESMBAGA1UEBwwJTnVyZW1iZXJnMSIwIAYDVQQKDBlUcnVzdCBTZXJ2aWNlIFByb3ZpZGVyIEFHMR8wHQYDVQQLDBZJbmZvcm1hdGlvbiBUZWNobm9sb2d5MB4XDTIxMDMxMjA4NDcxMVoXDTIyMDMxMjAwMDAwMFowgbwxFDASBgNVBAoMC0F3ZXNvbWUgVFBQMRUwEwYDVQQDDAxYUzJBIFNhbmRib3gxHjAcBgoJkiaJk/IsZAEZFg5hd2Vzb21lLXRwcC5kZTEWMBQGA1UECwwNSVQgZGVwYXJ0bWVudDEQMA4GA1UEBhMHR2VybWFueTEPMA0GA1UECAwGQmF5ZXJuMRIwEAYDVQQHDAlOdXJlbWJlcmcxHjAcBgNVBGEMFVBTRERFLUZBS0VOQ0EtSUQxMjM0NTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMDhK0Wjb9tFRZK11nG4kaUlrziheoHxFrbdG04J4TaQ5+C1BXFtvhXNHXoA50YxjPS2/r24SOG3dr+UV+kBPuTmCydo6nrW68NarTAHwSR4ue6AubPvomPoPcNVY85+71lQ8T0Rus4E2ey6tU7mOvUS9l9n6fjvR5wGVbjTb0gQXrygZvE6BRjMm7QwHCgYCDFrTQgsbwUX97iqzntuY0OH8Li9sfoiNyN60vw5PMKy6RDIWmCH64aniCRnu5LlzoPbWriLXcOE//Hgu+B3TxnO2ABWSMFA+eBTskGi5tHp4apoE8ltdWVRHohtWulxCY3VducV/beDpXYx9UnPL+ECAwEAAaN+MHwwegYIKwYBBQUHAQMEbjBsBgYEAIGYJwIwYjA5MBEGBwQAgZgnAQMMBlBTUF9BSTARBgcEAIGYJwECDAZQU1BfUEkwEQYHBACBmCcBBAwGUFNQX0lDDBlUcnVzdCBTZXJ2aWNlIFByb3ZpZGVyIEFHDApERS1GQUtFTkNBMA0GCSqGSIb3DQEBCwUAA4ICAQA2tFEMfPQywulze/OQ7N00w2KYJay8XWu4zdsA8wusHClH0Swcr/LzuBICTE3q6sfaW5+rUdGeMPA41k8X2K/3RNY7zwGcqPH8PvzoA2nwwPXapH18ewYqh3o7OVoF0M7x6YnXyeqAoRF4tLcOZdpIzg++q3E8q+YmKPqccweKsEPS4sazCSfSbEjAm+AuTUvVdgOTIAbDwgXfWBkCZOPGHmzY2GFQmlSUBUJgO2IZTTxB75PbIbYP/cLjE44UDU25Kq3zmBTWbpk4G+smZ6fnsRObs57TN+YF1U9z0suRFqVB3veQTxSUvyq9iMrR7fMjY3rfPJ/ceSOVeQgWSOjs6A4DUapjqrpAnmyzJTu5WfY29rb00bQKAcI640cmzWi5QO6UdFr0tGqNwu5nj7AThYqAvaV5JSzO5rNHYAyl/ktvldubTTzRbICecmCMtwpxj6DYW+1iffQgPT/JDZaTGcs0whRxkZqHrTxQL5A/ZClhy2Kv4PWnfUeor3goPZuoxWoDAfw/c51gAMvBayfqKvnRHOYt9m9Nw/Q7DeJiIG1zkcg6gzhWAyOnhTADbF75OguxDpaVfM7gTrDIp//eQbJpk2ndc9mGx08y9q5gT6VjV6FwX7jZZX9Hhftz4rGa2aVHejkDBg4V56BImvXb+gG8G69HYhyyqbLDGwDOUA==-----END CERTIFICATE-----
