# Note that applications will start in isolated mode, so you can safely use variables defined in app specific profile
# like ${localapp.schema.name} that will come from app-specific profile
common:
  apps:
    # On which port local applications will be started
    local:
      aspspprofile:
        # url aspsp profile in Postman
        port: 20010
        host: localhost
      certgenerator:
        port: 20011
        host: localhost
      consentmgmt:
        # url_cms in Postman
        port: 20012
        host: localhost
      ledgersapp:
        # url_ledgers in Postman
        port: 20013
        host: localhost
      ledgersgateway:
        # url_xs2a  in Postman
        port: 20014
        host: localhost
      onlinebanking:
        port: 20015
        host: localhost
      tpprest:
        port: 20016
        host: localhost
      onlinebankingui: # XS2A-Sandbox/oba-ui
        port: 4400 # This one is rather hardcoded in Docker-UI
        host: localhost
    # Which urls local sandbox applications will use to talk each with other
    mapping:
      aspsp: http://${common.apps.local.aspspprofile.host}:${common.apps.local.aspspprofile.port}
      certgenerator: http://${common.apps.local.certgenerator.host}:${common.apps.local.certgenerator.port}
      consentmgmt: http://${common.apps.local.consentmgmt.host}:${common.apps.local.consentmgmt.port}
      ledgersapp: http://${common.apps.local.ledgersapp.host}:${common.apps.local.ledgersapp.port}
      ledgersgateway: http://${common.apps.local.ledgersgateway.host}:${common.apps.local.ledgersgateway.port}
      onlinebanking: http://${common.apps.local.onlinebanking.host}:${common.apps.local.onlinebanking.port}
      tpprest: http://${common.apps.local.tpprest.host}:${common.apps.local.tpprest.port}

# Disable JMX to avoid collisions
spring:
  jmx:
    enabled: false
