# Alias xs2a at 8089 on host
server:
  port: ${common.apps.local.ledgersgateway.port}

spring:
  profiles:
    # FIXME: Maybe mock-qwac is not good idea
    active: postgres,mock-qwac,remote

aspsp-profile:
  baseurl: ${common.apps.mapping.aspsp}/api/v1
consent-service:
  baseurl: ${common.apps.mapping.consentmgmt}/api/v1
ledgers:
  url: ${common.apps.mapping.ledgersapp}
cms:
  url: ${common.apps.mapping.consentmgmt}
online-banking:
  url: ${common.apps.mapping.onlinebanking}/api/v1/consents/confirm/{userLogin}/{consentId}/{authorizationId}/{tan}

# To verify:
skip_ssl_certificate_verification: true

qwac-certificate-mock: -----BEGIN CERTIFICATE-----MIIFNjCCAx6gAwIBAgIEcQJvYzANBgkqhkiG9w0BAQsFADB4MQswCQYDVQQGEwJERTEQMA4GA1UECAwHQkFWQVJJQTESMBAGA1UEBwwJTnVyZW1iZXJnMSIwIAYDVQQKDBlUcnVzdCBTZXJ2aWNlIFByb3ZpZGVyIEFHMR8wHQYDVQQLDBZJbmZvcm1hdGlvbiBUZWNobm9sb2d5MB4XDTIwMDMwNDA5MTYxM1oXDTIxMDMwNDAwMDAwMFowgcExITAfBgNVBAoMGEZpY3Rpb25hbCBDb3Jwb3JhdGlvbiBBRzElMCMGCgmSJomT8ixkARkWFXB1YmxpYy5jb3Jwb3JhdGlvbi5kZTEfMB0GA1UECwwWSW5mb3JtYXRpb24gVGVjaG5vbG9neTEQMA4GA1UEBhMHR2VybWFueTEPMA0GA1UECAwGQmF5ZXJuMRIwEAYDVQQHDAlOdXJlbWJlcmcxHTAbBgNVBGEMFFBTRERFLUZBS0VOQ0EtODdCMkFDMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApLM+4noVMsJVHmdYpeLfAoT6ASyVedSTnhDc+uO9ZHBCW9CX2WdkL1M2ObG/qLJcI0kCiHE4wMmllgT+6Vec3Uce398406yGNLh95N9bEKjx+lIs7iM1KEmsrX2RjciStigMPu8nrTyZi8w8rlC7lCT0wQ63+u7W/Sr9guBUZCBmxWiWDOf4fQOsKhK0RvrP7Q4FeTsQEGdmwkQzQIzk0sNyDrVUqqs5qLqQJESTjQ1u9b2zQe0f14PPiNVFUIy0m/vxXl1O5pPiUlT8N+IAi9cHqUQxBdBtkvaAT6uFRJAPevGGtmQ66iEhl1pCfK5RpxnsS5GwS7vz81PYApPFIQIDAQABo34wfDB6BggrBgEFBQcBAwRuMGwGBgQAgZgnAjBiMDkwEQYHBACBmCcBAwwGUFNQX0FJMBEGBwQAgZgnAQIMBlBTUF9QSTARBgcEAIGYJwEEDAZQU1BfSUMMGVRydXN0IFNlcnZpY2UgUHJvdmlkZXIgQUcMCkRFLUZBS0VOQ0EwDQYJKoZIhvcNAQELBQADggIBABnAZg21fFw7qZ4ksOqj6l/Su61WmHSIxiDyoVQx3I1uaf4CM7vPn7anCduxCLmbyrqDgzV6gF00QkTZLhPeHbRf9g39wlxoOoOkuuIeo+Tq+xoIqJ7Nh+dDX4NJgbmNRlLFfpzftAQks+Xu9He+uze6twXMYYVLmPSJsfa1+aYYh1LroiXc/wcGVQeQ9mNmWR93ok4xryjKK0G1RfDM2gyRl36wBMDAf8SVCfEXlvwsMMC4Iue+CIlGXxgU7hKslRR3CPOpdi/nmXvuI+O8NXnOS4A3x8iM9erwOQgJ7g75p+kP/tMmWxU0LVKWqsQY+xBtp/UJ6LKXSS0ipK+Wc3OtIm+NSsFAo9oWwMI9wYRoyWzkfiklNLadBBJLN0RHuira87B0nNwWo7H3QomVuDkpwO2rfOgKlI+HltMYNSIUhMBxyGg18GoXZC3si0bNZx/NQFNM6oQjRVVgmnE81inc6g3KY7K/QQqYQW0d4vtR2LYEYqDYh0yiLhEDY+ztuEMa4OqgXpnmWx4Z8SE8WSRZwnBzBs6klJVDhg3SzfdX4wDh1SA3AqBx8Rl/FKkAdB/2gpMRHuTHHYJTPnJGwQOTWFO2I6raCY+yojcLpex2eIFJGJfP9IP9TulXYKzjCMBXLbUCRx+drTxd+1YAwv2rWrEyki2C5AqZQNKyXdMo-----END CERTIFICATE-----
