# Note that applications will start in isolated mode, so you can safely use variables defined in app specific profile
# like ${localapp.schema.name} that will come from app-specific profile
common:
  apps:
    # On which port local applications will be started
    local:
      aspspprofile:
        # url aspsp profile in Postman
        port: 20010
      certgenerator:
        port: 20011
      consentmgmt:
        # url_cms in Postman
        port: 20012
      ledgersapp:
        # url_ledgers in Postman
        port: 20013
      ledgersgateway:
        # url_xs2a  in Postman
        port: 20014
      onlinebanking:
        port: 20015
      tpprest:
        port: 20016
      onlinebankingui: # XS2A-Sandbox/oba-ui
        port: 4400 # This one is rather hardcoded in Docker-UI
    # Which urls local sandbox applications will use to talk each with other
    mapping:
      aspsp: http://localhost:${common.apps.local.aspspprofile.port}
      certgenerator: http://localhost:${common.apps.local.certgenerator.port}
      consentmgmt: http://localhost:${common.apps.local.consentmgmt.port}
      ledgersapp: http://localhost:${common.apps.local.ledgersapp.port}
      ledgersgateway: http://localhost:${common.apps.local.ledgersgateway.port}
      onlinebanking: http://localhost:${common.apps.local.onlinebanking.port}
      tpprest: http://localhost:${common.apps.local.tpprest.port}

# Disable JMX to avoid collisions
spring:
  jmx:
    enabled: false
