protocol:
  redirect:
    to-aspsp: "#{context.getLastRedirection().getRedirectTo()}"
    consent-accounts:
      result: ${protocol.embedded-ui-base-url}/from-aspsp?dest=#{urlSafe(context.getLastRedirection().getRedirectTo())}&serviceSessionId=#{context.getServiceSessionId()}
    parameters:
      provide-more: ${protocol.embedded-ui-base-url}/parameters/provide-more/#{execution.getId()}?q=#{urlSafe(context.getViolations().toString())}
  embedded-ui-base-url: http://localhost:5500
