spring:
  datasource:
    url: jdbc:tc:postgresql:12:////open_banking?TC_DAEMON=true&?TC_TMPFS=/testtmpfs:rw&TC_INITSCRIPT=init.sql
    username: postgres
    password: docker
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver

facade:
  encryption:
    providerName: BC
    algorithm: PBEWithSHA256And256BitAES-CBC-BC
    saltLength: 8
    iterationCount: 1024
    keySetPath: example-keyset.json
# Unused in the protocol, but imported through opba-db and expected to be injected by spring
bank-search:
  query: