### Authorization
GET http://localhost:8085/v1/banking/ais/accounts/
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
Service-Session-Password: qwerty
Fintech-User-ID: Anton_Brueckner
Fintech-Redirect-URL-NOK: http://localhost:5500/fintech-callback/nok
Service-Session-ID:
Authorization: MY-SUPER-FINTECH-ID
Fintech-Redirect-URL-OK: http://localhost:5500/fintech-callback/ok?redirectCode=163f947a-b6af-42a6-b356-32c32b68e557
Accept: application/json, text/plain, */*
PSU-IP-Address: 1.1.1.1
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) snap Chromium/81.0.4044.92 Chrome/81.0.4044.92 Safari/537.36
Compute-PSU-IP-Address: false
Bank-ID: 53c47f54-b9a4-465a-8f77-bc6cd5f0cf46
X-Request-ID: 43da4e2f-72cb-43bb-8afd-683104de57f9
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: cors
Sec-Fetch-Dest: empty
Referer: http://localhost:5500/initial
Accept-Language: en-US,en;q=0.9

> {%
client.global.set("location", response.headers.valueOf("Location"));
client.global.set("authorization-id", response.headers.valueOf("authorization-session-id"));
client.global.set("password", client.global.get("location").split("redirectCode=")[1]);
%}

### Association
POST http://localhost:8085/v1/psu/ais/{{authorization-id}}/for-approval/login?redirectCode={{password}}
accept: application/json
X-Request-ID: 163f947a-b6af-42a6-b356-32c32b68e557
Content-Type: application/json

{
  "login": "Anton_Brueckner",
  "password": "1234"
}

###

