openapi: 3.0.1
info:
  title: An include file to define common attributes
  version: 1.0.0
paths: {}

components:
  headers:
    Location:
      required: true
      description: |
        URL where User have to be redirected to in order to perform next step.
      example: "https://example.com/someservice/some-id/somepage?param=value"
      schema:
        type: string

    X-Request-ID:
      required: true
      description: |
        Unique ID that identifies this request through common workflow.
        Shall be contained in HTTP Response as well.
      example: "99391c7e-ad88-49ec-a2ad-99ddcb1f7721"
      schema:
        type: string
        format: uuid

    Service-Session-ID:
      required: true
      description: |
        Unique ID that identifies service session. Can be used for batch processing to correlate input and output.
      example: "99391c7e-ad88-49ec-a2ad-99ddcb1f7721"
      schema:
        type: string
        format: uuid

    Authorization-Session-ID:
      required: true
      description: |
        Unique ID that identifies authorization session.
      example: "99391c7e-ad88-49ec-a2ad-99ddcb1f7721"
      schema:
        type: string
        format: uuid

    Redirect-Code:
      required: true
      description: |
        Unique ID acts as a password protecting FinTech requested consent specification
      example: "99391c7e-ad88-49ec-a2ad-99ddcb1f7721"
      schema:
        type: string
        format: uuid

  parameters:
    Authorization:
      name: Authorization
      in: header
      required: true
      description: |
        Unique Token that identifies FinTech Session for this request.
      example: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6Ik15IGNvb2wgRmludGVjaCBBcHAiLCJpYXQiOjE1MTYyMzkwMjJ9.NfpSq7hot-1x3rZOaqRaSJzNnMw6ltX-9eqxcCQnGbI"
      schema:
        type: string

    ServiceSessionPassword:
      name: Service-Session-Password
      in: header
      required: true
      description: |
        Password to encrypt users' context
      example: "qwerty"
      schema:
        type: string

    Bank-ID:
      name: Bank-ID
      in: header
      required: false
      description: |
        A bank identifier, provided by TPP Bank Search API. To be provided by FinTech only if PsuConsentSession is missing.
      example: "1234-0XGJK"
      schema:
        type: string

    Fintech-User-ID:
      name: Fintech-User-ID
      in: header
      required: true
      description: |
        An End-User identifier, known by FinTech, that unique for each physical person.
        To be provided by FinTech with every request in order to validate the mapping of service request to the particular user.
      example: "1234-0XGJK"
      schema:
        type: string

    PSU-Consent-Session:
      name: PSU-Consent-Session
      in: header
      required: false
      description: |
        Unique Token that identifies PSU Consent Session for this request, if it is already available for given PSU by Fintech through previous requests.
        This Token is not designed to be parsed at Fintech side.
      example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwicHN1IjoiSm9obl9Eb2UiLCJjb25zZW50SWQiOiI3OGUyODUwMy0xMzZkLTRkODYtYjg0NC1lNWY1NTgyNTc2ZTUiLCJpYXQiOjE1MTYyMzkwMjJ9.4BHXUW9CH63ZTkxKktFFrVGCUuFltFyivHxk3LVg2bs"
      schema:
        type: string

    Service-Session-ID:
      name: Service-Session-ID
      in: header
      required: false
      description: |
        Unique ID that identifies service session. Can be used for batch processing to correlate input and output.
      example: "99391c7e-ad88-49ec-a2ad-99ddcb1f7721"
      schema:
        type: string
        format: uuid

    X-Request-ID:
      name: X-Request-ID
      in: header
      required: true
      description: |
        Unique ID that identifies this request through common workflow.
        Shall be contained in HTTP Response as well.
      example: "99391c7e-ad88-49ec-a2ad-99ddcb1f7721"
      schema:
        type: string
        format: uuid

    X-Timestamp-UTC:
      name: X-Timestamp-UTC
      in: header
      required: false
      description: |
        The timestamp of the operation.
      example: "2020-04-14T08:46:33.629Z"
      schema:
        type: string

    X-Operation-Type:
      name: X-Operation-Type
      in: header
      required: false
      description: |
        The type of the fintech request.
      example: "AIS"
      schema:
        type: string

    X-Pis-Psu-Authentication-Required:
      name: X-Pis-Psu-Authentication-Required
      in: header
      description: |
        If false, login form to OPBA will not be displayed as there might be nothing to share for payments, so
        that authentication is not necessary. If absent or true - login form for payments will be displayed.
      example: "true"
      schema:
        type: boolean
        default: "true"

    X-Request-Signature:
      name: X-Request-Signature
      in: header
      required: false
      description: |
        A signature of the request by the TPP fintech.
      schema:
        type: string

    Fintech-ID:
      name: Fintech-ID
      in: header
      required: false
      description: |
        Unique ID that identifies fintech.
      example: "fintech_123"
      schema:
        type: string

    Fintech-Redirect-URL-OK:
      name: Fintech-Redirect-URL-OK
      in: header
      desription: |
        This header provides the desired URL where PSU will be redirected back after authorisation session in case of
        successful authorisation. This URL might contain unique Identifier of this User and/or Session,
        recognisable by FinTech.
        Since authorisation may be mandated by the bank at any time, this header to be included to all
        service requests, even if PsuConsentSession already exists.
      required: true
      schema:
        type: string
      example: "https://example.com/myservice/sf3-3r33-3535?authResult=success"

    Fintech-Redirect-URL-NOK:
      name: Fintech-Redirect-URL-NOK
      in: header
      desription: |
        This header provides the desired URL where PSU will be redirected back  after authorisation session in case of
        unsuccessful authorisation (i.e. PSU's authorisation reject, technical failure, lack of credentials etc.).
        This URL might contain unique Identifier of this User and/or Session,
        recognisable by FinTech.
        Since authorisation may be mandated by the bank at any time, this header to be included to all
        service requests, even if PsuConsentSession already exists.
      required: true
      schema:
        type: string
      example: "https://example.com/myservice/sf3-3r33-3535/failure"


  responses:
    401_UNAUTHORIZED:
      description: |
        Unauthorised. Access token absent or invalid.
      headers:
        X-Request-ID:
          $ref: "./tpp_banking_api_commons.yml#/components/headers/X-Request-ID"
      content:
        application/json:
          schema:
            $ref: "./tpp_banking_api_commons.yml#/components/schemas/generalError"

    404_NOT_FOUND:
      description: |
        Resource not found or path parameter is wrong.
      headers:
        X-Request-ID:
          $ref: "./tpp_banking_api_commons.yml#/components/headers/X-Request-ID"
      content:
        application/json:
          schema:
            $ref: "./tpp_banking_api_commons.yml#/components/schemas/generalError"

  schemas:
    accountReference:
      description: |
        Reference to an account by either:
          * IBAN, of a payment accounts, or
          * BBAN, for payment accounts if there is no IBAN, or
          * the Primary Account Number (PAN) of a card, can be tokenised by the ASPSP due to PCI DSS requirements, or
          * the Primary Account Number (PAN) of a card in a masked form, or
          * an alias to access a payment account via a registered mobile phone number (MSISDN).
      type: object
      properties:
        iban:
          $ref: "#/components/schemas/iban"
        bban:
          $ref: "#/components/schemas/bban"
        pan:
          $ref: "#/components/schemas/pan"
        maskedPan:
          $ref: "#/components/schemas/maskedPan"
        msisdn:
          $ref: "#/components/schemas/msisdn"
        currency:
          $ref: "#/components/schemas/currencyCode"

    iban:
      type: string
      description: International bank account number ISO 31616.
      pattern: "[A-Z]{2,2}[0-9]{2,2}[a-zA-Z0-9]{1,30}"
      example: "FR7612345987650123456789014"

    bban:
      description: |
        Basic Bank Account Number (BBAN) Identifier.

        This data element can be used in the body of the Consent request.
          Message for retrieving Account access Consent from this Account. This
          data elements is used for payment Accounts which have no IBAN.
          ISO20022: Basic Bank Account Number (BBAN).

          Identifier used nationally by financial institutions, i.e., in individual countries,
          generally as part of a National Account Numbering Scheme(s),
          which uniquely identifies the account of a customer.
      type: string
      pattern: "[a-zA-Z0-9]{1,30}"
      example: "BARC12345612345678"

    maskedPan:
      description: |
        Masked Primary Account Number.
      type: string
      maxLength: 35
      example: "123456xxxxxx1234"

    msisdn:
      type: string
      maxLength: 35
      description: Mobile phone number.
      example: "+49 170 1234567"

    pan:
      description: |
        Primary Account Number according to ISO/IEC 7812.
      type: string
      maxLength: 35
      #According to ISO the following should be valid.
      #maxLength: 19
      #minLength: 8
      #pattern: "[0-9]{8,19}"
      example: "5409050000000000"

    amount:
      type: object
      required:
        - currency
        - amount
      properties:
        currency:
          $ref: "#/components/schemas/currencyCode"
        amount:
          $ref: "#/components/schemas/amountValue"
      example:
        {
          "currency": "EUR",
          "amount": "123"
        }

    amountValue:
      description: |
        The amount given with fractional digits, where fractions must be compliant to the currency definition.
        Up to 14 significant figures. Negative amounts are signed by minus.
        The decimal separator is a dot.

        **Example:**
        Valid representations for EUR with up to two decimals are:

          * 1056
          * 5768.2
          * -1.50
          * 5877.78
      type: string
      pattern: "-?[0-9]{1,14}(\\\\.[0-9]{1,3})?"
      example: "5877.78"

    currencyCode:
      description: |
        ISO 4217 Alpha 3 currency code.
      type: string
      pattern: "[A-Z]{3}"
      example: "EUR"

    bicfi:
      description: |
        BICFI
      type: string
      pattern: "[A-Z]{6,6}[A-Z2-9][A-NP-Z0-9]([A-Z0-9]{3,3}){0,1}"
      example: "AAAADEBBXXX"

    address:
      type: object
      required:
        - country
      properties:
        streetName:
          type: string
          maxLength: 70
        buildingNumber:
          type: string
        townName:
          type: string
        postCode:
          type: string
        country:
          $ref: "#/components/schemas/countryCode"
      example:
        {
          street: "rue blue",
          buildingnNumber: "89",
          city: "Paris",
          postalCode: "75000",
          country: "FR"
        }

    countryCode:
      description: ISO 3166 ALPHA2 country code.
      type: string
      pattern: "[A-Z]{2}"
      example: "SE"

    creditorName:
      description: Creditor Name.
      type: string
      maxLength: 70
      example: "Creditor Name"

    creditorAgentName:
      description: Creditor agent name.
      type: string
      maxLength: 70
      example: Creditor Agent Name

    remittanceInformationUnstructured:
      description: |
        Unstructured remittance information.
      type: string
      maxLength: 140
      example: "Ref Number Merchant"

    generalError:
      type: object
      properties:
        code:
          type: string
          example: "ERROR_CODE"
        message:
          type: string
          example: "Error description message"
