openapi: 3.0.1
info:
  version: "1.0.0"
  title: Open Banking Gateway Tpp Token API
  description: >-
    This API provides FinTech with an Endpoint to retrieve a token after redirection from the consent authorization API
externalDocs:
  url: "https://adorsys.github.com/open-banking-gateway"


paths:

  /v1/banking/token:
    post:
      tags:
      - TppToken
      operationId: code2TokenGET
      summary: Issues an incremental bank search request to the TppBankSearchApi.
      description: Issues an incremental bank search request to the TppBankSearchApi.
      parameters:
      #header
      - $ref: "#/components/parameters/X-Request-ID"
      #query
      - name: redirectCode
        in: query
        required: true
        schema:
          $ref: '#/components/schemas/redirectCode'
      responses:
        '201':
          $ref: "#/components/responses/201_PsuConsentSession"
        '401':
          $ref: '#/components/responses/401_UNAUTHORIZED'

components:
  headers:
    X-Request-ID:
      required: true
      description: |
        Unique ID that identifies this request through common workflow.
        Shall be contained in HTTP Response as well.
      example: "99391c7e-ad88-49ec-a2ad-99ddcb1f7721"
      schema:
        type: string
        format: uuid

  parameters:
    X-Request-ID:
      name: X-Request-ID
      in: header
      required: true
      description: |
        Unique ID that identifies this request through common workflow.
        Shall be contained in HTTP Response as well.
      example: "99391c7e-ad88-49ec-a2ad-99ddcb1f7721"
      schema:
        type: string
        format: uuid


  responses:
    401_UNAUTHORIZED:
      description: |
        Unauthorised. Access token absent or invalid.
      headers:
        X-Request-ID:
          $ref: "#/components/headers/X-Request-ID"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/generalError"

    201_PsuConsentSession:
      description: Response containing the service profile of a bank.
      headers:
        X-Request-ID:
          $ref: '#/components/headers/X-Request-ID'
      content:
        application/json:
          schema:
            type: object
            properties:
              userProfile:
                type: array
                items:
                  $ref: '#/components/schemas/PsuConsentSession'


  schemas:

    generalError:
      type: object
      properties:
        code:
          type: string
          example: "ERROR_CODE"
        message:
          type: string
          example: "Error description message"

    # Search and bank profile
    PsuConsentSession:
      title: |
        The representation of a PSU consent session. We call this a session 
        because it hase a life cycle including an expiration.
      type: object
      properties:
        consentId:
          description: unique identifier of this psu consent session.
          type: string
        consentToken:
          description: |
            signed descriptor of the consent session. Eventualy including 
            consent data.
          type: string
          example: ejxs.wersdzxxc23r.asdf

    redirectCode:
      name: redirectCode
      in: query
      required: true
      schema:
        type: string

  securitySchemes:
    BearerAuthOAuth:
      description: |
        Bearer Token.
      type: http
      scheme: bearer
    accessCode:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: 'http://example.com/oauth/auth'
          tokenUrl: 'http://example.com/oauth/token'
          scopes:
            write: allows modifying resources
            read: allows reading resources
