openapi: 3.0.1
info:
  version: "1.0.0"
  title: Open Banking Gateway Tpp Token API
  description: >-
    This API provides FinTech with an Endpoint to confirm consent after redirection from the consent authorization API
externalDocs:
  url: "https://adorsys.github.com/open-banking-gateway"


paths:

  /v1/banking/consent/confirm:
    post:
      tags:
        - ConsentConfirmation
      operationId: confirmConsent
      summary: Issues new PSU Consent Session Token.
      description: TBD
      parameters:
      #common header parameter
        - $ref: "./tpp_banking_api_commons.yml#/components/parameters/Authorization"
        - $ref: "./tpp_banking_api_commons.yml#/components/parameters/X-Request-ID"
      responses:
        '200':
          $ref: "#/components/responses/200_PsuConsentSession"
        '401':
          $ref: './tpp_banking_api_commons.yml#/components/responses/401_UNAUTHORIZED'
        '404':
          $ref: './tpp_banking_api_commons.yml#/components/responses/404_NOT_FOUND'

components:
  responses:

    200_PsuConsentSession:
      description: Response containing the service profile of a bank.
      headers:
        X-Request-ID:
          $ref: "./tpp_banking_api_commons.yml#/components/headers/X-Request-ID"
      #NO RESPONSE BODY

  securitySchemes:
    BearerAuthOAuth:
      description: |
        Bearer Token.
      type: http
      scheme: bearer
    accessCode:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: 'http://example.com/oauth/auth'
          tokenUrl: 'http://example.com/oauth/token'
          scopes:
            write: allows modifying resources
            read: allows reading resources
