openapi: 3.0.1
info:
  version: "1.0.0"
  title: Open Banking Gateway Tpp Token API
  description: >-
    This API provides FinTech with an Endpoint to confirm consent after redirection from the consent authorization API
externalDocs:
  url: "https://adorsys.github.com/open-banking-gateway"


paths:

  /v1/banking/consent/confirm:
    post:
      tags:
        - ConsentConfirmation
      operationId: confirmConsent
      summary: Issues new PSU Consent Session Token.
      description: TBD
      parameters:
      #common header parameter
        - $ref: "./tpp_banking_api_commons.yml#/components/parameters/Authorization"
        - $ref: "./tpp_banking_api_commons.yml#/components/parameters/X-Request-ID"
      #query
        - $ref: '#/components/parameters/redirectCode'
      responses:
        '200':
          $ref: "#/components/responses/200_PsuConsentSession"
        '401':
          $ref: './tpp_banking_api_commons.yml#/components/responses/401_UNAUTHORIZED'
        '404':
          $ref: './tpp_banking_api_commons.yml#/components/responses/404_NOT_FOUND'

components:
  parameters:

    redirectCode:
      name: redirectCode
      in: query
      required: true
      schema:
        type: string


  responses:

    200_PsuConsentSession:
      description: Response containing the service profile of a bank.
      headers:
        X-Request-ID:
          $ref: "./tpp_banking_api_commons.yml#/components/headers/X-Request-ID"
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PsuConsentSessionResponse'

  schemas:

    PsuConsentSession:
      title: |
        The representation of a PSU consent session. We call this a session
        because it hase a life cycle including an expiration.
      description: |
        Unique Token that identifies PSU Consent Session for this request, if it is already available for given PSU by Fintech through previous requests.
        This Token is not designed to be parsed at Fintech side.
      properties:
        value:
          type: string
      example: "Confirmed"

    PsuConsentSessionResponse:
      type: object
      properties:
        psuConsentSession:
          $ref: '#/components/schemas/PsuConsentSession'


  securitySchemes:
    BearerAuthOAuth:
      description: |
        Bearer Token.
      type: http
      scheme: bearer
    accessCode:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: 'http://example.com/oauth/auth'
          tokenUrl: 'http://example.com/oauth/token'
          scopes:
            write: allows modifying resources
            read: allows reading resources
