@startuml
legend top left
  <b>Embedded initial authorization phase</b>
endlegend

actor User

collections TppBackend

box "TPP API"
control TppBankingApiAisController
control ConsentServiceController
participant FacadeResponseMapper
endbox

box "OPBA-Facade"
collections FacadeService
database Database
participant ServiceContextProvider
participant ProtocolSelector
participant Spring
participant ProtocolResultHandler
endbox

box "XS2A-Protocol"
participant Xs2aListAccountsEntrypoint
participant Xs2aUpdateAuthorization
participant Xs2aFromAspspRedirect
participant Xs2aResultBodyExtractor
collections Xs2aServices
participant OutcomeMapper
endbox

boundary ASPSP

== User authorizes this request (embedded to provide i.e. PSU id) ==
loop Until user input has not enough parameters
User [#green]-> TppBackend ++ : POST /consent/embedded\n(Update context with 'Consent valid until', which accounts, etc.)
TppBackend [#green]-> ConsentServiceController ++ : embeddedUsingPOST
ConsentServiceController [#green]-> FacadeService ++ : Facade.execute()
FacadeService [#green]-> ServiceContextProvider ++ : Create facade context from request
FacadeService <-[#green] ServiceContextProvider -- : ServiceContext
FacadeService [#green]-> ProtocolSelector ++: Select bank protocol by using authorization session id
ProtocolSelector [#green]-> Database ++ : Read authorization session using authId from request
Database [#green]-> ProtocolSelector -- : AuthorizationSession
ProtocolSelector [#green]-> Database ++ : Read bank protocol using AuthorizationSession.bankProtocolId
Database [#green]-> ProtocolSelector -- : BankProtocol
ProtocolSelector [#green]-> FacadeService -- : BankProtocol
FacadeService [#green]-> Spring ++ : Find bean - Bean(BankProtocol.protocolBeanName) extends Action
FacadeService <-[#green] Spring -- : It is Xs2aUpdateAuthorization service bean
FacadeService [#green]-> Xs2aListAccountsEntrypoint ++ : Xs2aListAccountsEntrypoint.execute(ServiceContext)
Xs2aListAccountsEntrypoint [#green]-> Xs2aServices ++
Xs2aServices [#green]-> Database ++ : Consent for service session
Xs2aServices <-[#green] Database -- : No consent
alt User supplied not enough data
  Xs2aServices [#green]-> Xs2aServices : Validate API input -\ndo we have enough data (Mocked execution)
  Xs2aServices [#green]-> Xs2aListAccountsEntrypoint -- : ValidationIssue[] -> User input has missing parameters
  Xs2aListAccountsEntrypoint [#green]-> OutcomeMapper ++ : Translate ValidationIssue[]
  OutcomeMapper [#green]-> Xs2aListAccountsEntrypoint -- : ContextBasedValidationErrorResult
  Xs2aListAccountsEntrypoint [#green]-> FacadeService -- : ContextBasedValidationErrorResult
  FacadeService [#green]-> ProtocolResultHandler ++ : Translate ContextBasedValidationErrorResult -> FacadeStartAuthorizationResult
  ProtocolResultHandler [#green]-> Database ++ : Authorization session present?
  Database [#green]-> ProtocolResultHandler -- : AuthorizationSession
  ProtocolResultHandler [#green]-> FacadeService -- : FacadeRedirectResult
  FacadeService [#green]-> ConsentServiceController ++ : process FacadeRedirectResult
  ConsentServiceController [#green]-> FacadeResponseMapper ++ : translate FacadeRedirectResult
  FacadeResponseMapper [#green]-> ConsentServiceController -- : This is 303 code with redirection to Embedded authorization dynamic form continuation
  ConsentServiceController [#green]-> TppBackend  : 303 Embedded authorization
  TppBackend [#green]-> User : 303 Embedded authorization
else User supplied all necessary parameters
  Xs2aServices [#green]-> Xs2aServices ++ : User input OK
end
end

Xs2aServices [#green]-> Xs2aServices : Switch to real execution mode
Xs2aServices [#green]-> ASPSP ++ : Initiate consent
ASPSP [#green]-> Xs2aServices -- : Redirect authorization required
Xs2aServices [#green]-> Xs2aListAccountsEntrypoint ++ : Redirect to ASPSP required
deactivate Xs2aServices
Xs2aListAccountsEntrypoint [#green]-> OutcomeMapper ++ : Translate 'Redirect to ASPSP required'
OutcomeMapper [#green]-> Xs2aListAccountsEntrypoint -- : ContextBasedAuthorizationRequiredResult
Xs2aListAccountsEntrypoint [#green]-> FacadeService -- : ContextBasedAuthorizationRequiredResult
FacadeService [#green]-> ProtocolResultHandler ++ : Translate RedirectionResult -> FacadeRedirectResult
ProtocolResultHandler [#green]-> FacadeService -- : FacadeRedirectResult
FacadeService [#green]-> ConsentServiceController -- : FacadeRedirectResult
ConsentServiceController [#green]-> FacadeResponseMapper ++ : translate FacadeRedirectResult
FacadeResponseMapper [#green]-> ConsentServiceController -- : This is 303 code with redirection to ASPSP authorization page
ConsentServiceController [#green]-> TppBackend -- : 303 Redirect to ASPSP
TppBackend [#green]-> User -- : 303 ASPSP 'Login page'
@enduml
