@startuml
legend top left
  <b>Combined</b>
  embedded (Extra user parameters)
  and redirect (ASPSP authorization)
  authorization when  <b>consent is missing</b>
endlegend

actor FinTech
actor User

collections TppBackend

box "TPP API"
control TppBankingApiAisController
control ConsentServiceController
participant FacadeResponseMapper
endbox

box "OPBA-Facade"
collections FacadeService
database Database
participant ServiceContextProvider
participant ProtocolSelector
participant Spring
participant ProtocolResultHandler
endbox

box "XS2A-Protocol"
participant Xs2aListAccountsEntrypoint
participant Xs2aUpdateAuthorization
participant Xs2aFromAspspRedirect
participant Xs2aResultBodyExtractor
collections Xs2aServices
participant OutcomeMapper
endbox

boundary ASPSP
== ASPSP reports consent authorization OK ==
ASPSP [#magenta]-> User : Done
ASPSP [#magenta]-> TppBackend : GET /from/aspsp/ok webhook
TppBackend [#magenta]-> ConsentServiceController : fromAspspOkUsingGET
ConsentServiceController [#magenta]-> FacadeService : Facade.execute()
FacadeService [#magenta]-> ServiceContextProvider : Create facade context from request
FacadeService <-[#magenta] ServiceContextProvider : ServiceContext
FacadeService [#magenta]-> ProtocolSelector : Select bank protocol by using authorization session id
ProtocolSelector [#magenta]-> Database : Read authorization session
Database [#magenta]-> ProtocolSelector: Bank protocol id from authorization session
ProtocolSelector [#magenta]-> FacadeService : BankProtocol
FacadeService [#magenta]-> Spring : Find bean - Bean(BankProtocol.protocolBeanName) extends Action
FacadeService <-[#magenta] Spring : It is Xs2aFromAspspRedirect service bean
Xs2aFromAspspRedirect [#magenta]-> Xs2aServices : Bank approved consent
Xs2aServices [#magenta]-> Database : Persist consent and its context
Xs2aServices [#magenta]-> Xs2aFromAspspRedirect : Consent acquired
Xs2aFromAspspRedirect [#magenta]-> OutcomeMapper : Translate 'Consent acquired'
OutcomeMapper [#magenta]-> Xs2aFromAspspRedirect : ConsentAcquiredResult
Xs2aFromAspspRedirect [#magenta]-> FacadeService : ConsentAcquiredResult
FacadeService [#magenta]-> ProtocolResultHandler : Translate ConsentAcquiredResult -> FacadeRedirectResult
TppBankingApiAisController [#magenta]-> FacadeResponseMapper : translate FacadeRedirectResult
FacadeResponseMapper [#magenta]-> TppBankingApiAisController : This is 303 code with redirection to FinTech
TppBankingApiAisController [#magenta]-> TppBackend : 303 Redirect to FinTech
TppBackend [#magenta]-> User : 303 FinTech 'Thanks for consent' page

== Fintech receives notification that consent is received ==
User [#orange]-> FinTech
@enduml
