@startuml
legend top left
  <b>Initial request</b>
  TppBackend that enters embedded authorization mode
endlegend

actor FinTech

collections TppBackend

box "TPP API"
control TppBankingApiAisController
control ConsentServiceController
participant FacadeResponseMapper
endbox

box "OPBA-Facade"
collections FacadeService
database Database
participant ServiceContextProvider
participant ProtocolSelector
participant Spring
participant ProtocolResultHandler
endbox

box "XS2A-Protocol"
participant Xs2aListAccountsEntrypoint
participant Xs2aUpdateAuthorization
participant Xs2aFromAspspRedirect
participant Xs2aResultBodyExtractor
collections Xs2aServices
participant OutcomeMapper
endbox

== FinTech asks for user account list ==
FinTech [#blue]-> TppBackend ++ : GET /accounts\n(Fintech user info, bank id, etc.)
TppBackend [#blue]-> TppBankingApiAisController ++ : getAccounts
TppBankingApiAisController [#blue]-> FacadeService ++ : Facade.execute()
FacadeService [#blue]-> ServiceContextProvider ++ : Create facade context from request
FacadeService <-[#blue] ServiceContextProvider -- : ServiceContext
FacadeService [#blue]-> ProtocolSelector ++ : Select bank protocol from request type and bank id
ProtocolSelector [#blue]-> Database ++ : Read bank protocol using bank uuid and action id
Database [#blue]-> ProtocolSelector -- : BankProtocol
ProtocolSelector [#blue]-> FacadeService -- : BankProtocol
FacadeService [#blue]-> Spring ++ : Find bean - Bean(BankProtocol.protocolBeanName) extends Action
FacadeService <-[#blue] Spring -- : It is Xs2aListAccountsEntrypoint service bean
FacadeService [#blue]-> Xs2aListAccountsEntrypoint ++ : Xs2aListAccountsEntrypoint.execute(ServiceContext)
Xs2aListAccountsEntrypoint [#blue]-> Xs2aServices ++
Xs2aServices [#blue]-> Database ++ : Consent for service session
Xs2aServices <-[#blue] Database -- : No consent
Xs2aServices [#blue]-> Xs2aServices : Validate API input -\ndo we have enough data (Mocked execution)
Xs2aServices [#blue]-> Xs2aListAccountsEntrypoint -- : ValidationIssue[] -> User input has missing parameters
Xs2aListAccountsEntrypoint [#blue]-> OutcomeMapper ++ : Translate ValidationIssue[]
OutcomeMapper [#blue]-> Xs2aListAccountsEntrypoint -- : ContextBasedValidationErrorResult
Xs2aListAccountsEntrypoint [#blue]-> FacadeService -- : ContextBasedValidationErrorResult
FacadeService [#blue]-> ProtocolResultHandler ++ : Translate ContextBasedValidationErrorResult -> FacadeStartAuthorizationResult
ProtocolResultHandler [#blue]-> Database ++ : Authorization session present?
Database [#blue]-> ProtocolResultHandler -- : No authorization session
ProtocolResultHandler [#blue]-> Database ++ : Create authorization session
ProtocolResultHandler <-[#blue] Database -- : New authorization session
ProtocolResultHandler [#blue]-> FacadeService -- : FacadeStartAuthorizationResult
FacadeService [#blue]-> TppBankingApiAisController -- : process FacadeStartAuthorizationResult
TppBankingApiAisController [#blue]-> FacadeResponseMapper ++ : translate FacadeStartAuthorizationResult
FacadeResponseMapper [#blue]-> TppBankingApiAisController -- : This is 202 code with redirection to Embedded authorization
TppBankingApiAisController [#blue]-> TppBackend -- : 202 Embedded authorization
TppBackend [#blue]-> FinTech -- : 202 Embedded authorization with dynamic form
FinTech [#blue]-> FinTech: Store <b>service session id</b>
@enduml
