openapi: 3.0.1
info:
  version: "1.0.0"
  title: Open Banking Gateway Tpp Token API
  description: >-
    This API provides FinTech with an Endpoint to confirm consent after redirection from the consent authorization API
externalDocs:
  url: "https://adorsys.github.com/open-banking-gateway"


paths:
  /v1/banking/consents/{auth-id}/confirm:
    post:
      tags:
        - ConsentConfirmation
      operationId: confirmConsent
      summary: Issues new PSU Consent Session Token.
      description: TBD
      parameters:
      #path
        - $ref: "#/components/parameters/auth-id"
      #common header parameter
        - $ref: "./tpp_banking_api_commons.yml#/components/parameters/X-Timestamp-UTC"
        - $ref: "./tpp_banking_api_commons.yml#/components/parameters/X-Request-Signature"
        - $ref: "./tpp_banking_api_commons.yml#/components/parameters/Fintech-ID"
        - $ref: "./tpp_banking_api_commons.yml#/components/parameters/X-Request-ID"
        - $ref: "./tpp_banking_api_commons.yml#/components/parameters/ServiceSessionPassword"
        - $ref: "./tpp_banking_api_commons.yml#/components/parameters/FintechDataPassword"
      responses:
        '200':
          $ref: "#/components/responses/200_PsuConsentSession"
        '401':
          $ref: './tpp_banking_api_commons.yml#/components/responses/401_UNAUTHORIZED'
        '404':
          $ref: './tpp_banking_api_commons.yml#/components/responses/404_NOT_FOUND'

  /v1/banking/payments/{auth-id}/confirm:
    post:
      tags:
        - PaymentConfirmation
      operationId: confirmPayment
      summary: Issues new PSU Consent Session Token.
      description: TBD
      parameters:
        #path
        - $ref: "#/components/parameters/auth-id"
        #common header parameter
        - $ref: "./tpp_banking_api_commons.yml#/components/parameters/X-Timestamp-UTC"
        - $ref: "./tpp_banking_api_commons.yml#/components/parameters/X-Request-Signature"
        - $ref: "./tpp_banking_api_commons.yml#/components/parameters/Fintech-ID"
        - $ref: "./tpp_banking_api_commons.yml#/components/parameters/X-Request-ID"
        - $ref: "./tpp_banking_api_commons.yml#/components/parameters/ServiceSessionPassword"
        - $ref: "./tpp_banking_api_commons.yml#/components/parameters/FintechDataPassword"
      responses:
        '200':
          $ref: "#/components/responses/200_PsuPaymentSession"
        '401':
          $ref: './tpp_banking_api_commons.yml#/components/responses/401_UNAUTHORIZED'
        '404':
          $ref: './tpp_banking_api_commons.yml#/components/responses/404_NOT_FOUND'

components:
  parameters:
    auth-id:
      name: auth-id
      in: path
      required: true
      description: |
        Used to distinguish between different consent authorization processes started by the same PSU.
        Also included in the corresponding cookie path to limit visibility of the consent cookie to the
        corresponding consent process.
      example: abc123
      schema:
        type: string

  responses:
    200_PsuConsentSession:
      description: Response containing the service profile of a bank.
      headers:
        X-Request-ID:
          $ref: "./tpp_banking_api_commons.yml#/components/headers/X-Request-ID"
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PsuConsentSessionResponse'
    200_PsuPaymentSession:
      description: Response containing the service profile of a bank.
      headers:
        X-Request-ID:
          $ref: "./tpp_banking_api_commons.yml#/components/headers/X-Request-ID"
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PsuPaymentSessionResponse'

  schemas:
    PsuConsentSessionResponse:
      type: object
      properties:
        # To be renamed to PSU-ASPSP-Key ID
        authorizationSessionId:
          type: string
          format: uuid
    PsuPaymentSessionResponse:
      type: object
      properties:
        # To be renamed to PSU-ASPSP-Key ID
        authorizationSessionId:
          type: string
          format: uuid
