spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    data-password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

hbci:
  users:
    - login: anton.brueckner
      pin: 12345
      tan: 123456
      sca-method-list:
        sca-0: SMS on your phone
      accounts:
        - DE22500105175827542519
        - DE71500105179185286653
      transactions:
        DE71500105179185286653:
          - DK9150513599717134:
             amount: 100
             currency: EUR
             date: 2019-01-01T01:00:00
          - DK9150513599717134:
              amount: 30
              currency: EUR
              date: 2019-06-07T08:00:00
          - UA429912181258651749888998636:
              amount: 90
              currency: EUR
              date: 2020-01-02T09:00:00

    - login: max.musterman
      pin: 12345
      tan: 123456
      sca-method-list:
        sca-0: SMS on your phone
        sca-1: Email with TAN
      accounts:
        - DE16500105173466865655
        - DE67500105172278292697
      transactions:
        DE16500105173466865655:
          - AE170262989187616965653:
              amount: 30
              currency: EUR
              date: 2020-01-01T01:00:00
          - UA107659944284963696317637511:
              amount: 14.55
              currency: EUR
              date: 2019-06-07T08:30:00
          - DE59500105172584189131:
              amount: 400
              currency: EUR
              date: 2020-02-02T09:30:00

    # To be used for payments
    - login: adorsys
      pin: 12345
      tan: 123456
      sca-method-list:
        sca-0: SMS on your phone
        sca-1: Email with TAN
      accounts:
        - DE89500105175119697587

flowable:
  process-definition-location-prefix: classpath*:/processes/**/