spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    data-password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

hbci:
  banks:
    withAnonymousBpd:
      anonBpd: true
      users:
        - anton.brueckner
        - max.musterman
        - adorsys
    withoutAnonymousBpd:
      anonBpd: false
      users:
        - anton.brueckner
        - max.musterman
        - adorsys

  users:
    - login: anton.brueckner
      realname: Brueckner Anton
      pin: 12345
      tan: 123456
      sca-method-list:
        sca-0: SMS on your phone
      accounts:
          - number: 5827542519
            currency: EUR
            balalce: 100
          - number: 9185286653
            currency: EUR
            balalce: 30
      transactions:
        "5827542519":
          - DK9150513599717134:
             amount: 100
             currency: EUR
             date: 2019-01-01T01:00:00
          - DK9150513599717134:
              amount: 30
              currency: EUR
              date: 2019-06-07T08:00:00
          - UA429912181258651749888998636:
              amount: 90
              currency: EUR
              date: 2020-01-02T09:00:00

    - login: max.musterman
      realname: Musterman Max
      pin: 12345
      tan: 123456
      sca-method-list:
        sca-0: SMS on your phone
        sca-1: Email with TAN
      accounts:
        - number: 3466865655
          currency: EUR
          balalce: 200
        - number: 2278292697
          currency: EUR
          balalce: 130
      transactions:
        "3466865655":
          - AE170262989187616965653:
              amount: 30
              currency: EUR
              date: 2020-01-01T01:00:00
          - UA107659944284963696317637511:
              amount: 14.55
              currency: EUR
              date: 2019-06-07T08:30:00
          - DE59500105172584189131:
              amount: 400
              currency: EUR
              date: 2020-02-02T09:30:00

    # To be used for payments
    - login: adorsys
      realname: John Doe
      pin: 12345
      tan: 123456
      sca-method-list:
        sca-0: SMS on your phone
        sca-1: Email with TAN
      accounts:
        - number: 119697587
          currency: EUR
          balalce: 200

flowable:
  process-definition-location-prefix: classpath*:/processes/**/