@startuml
autonumber "<b><color blue>[00]"

PSU -> "TPP (PISP)" as TPP ++ :  GET PSU client bank id
return Bank id
PSU -> TPP ++ : Pay 100EUR to IBAN 12345
TPP -> "Open banking gateway" as OBA ++ : View parameters to perform\npayment for client to IBAN 12345
OBA -> "BPMN engine" as BPMN ++ : Compute parameters required\nfor given client and bank
return GEO_LOCATION
return GEO_LOCATION - client location necessary
TPP -> PSU : Read client's geo location
PSU -> TPP : Geo location = (54.32,32.32)
TPP -> OBA ++ : Initiate payment to\nIBAN 12345 with\nGEO_LOCATION = (54.32,32.32)
OBA -> BPMN ++ : Initiate payment to\nIBAN 12345 with\nGEO_LOCATION = (54.32,32.32)
BPMN -> "Computed\nXS2A call sequence" as XS2ASeq ++ : Execute
XS2ASeq -> ASPSP ++ : Payment initiation request
return Payment initiation response
loop SCA Authorization
  ASPSP -> PSU : SCA challenge
  PSU -> ASPSP : Challenge result
end
XS2ASeq -> ASPSP ++ : Payment status request
return Payment status response
return Payment complete
return Payment complete
return Payment complete
return Payment complete
@enduml