# Builds Pull-requests to key branches
name: Pull request CI with maven and npm. Builds backend and frontend

on:
  pull_request:
    branches:
      - develop
      - master
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build project and run default test suite
        run: ./scripts/build_and_test.sh