name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Build and Upload Release
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Create releases
        run: |
          chmod +x ./scripts/release-scripts/release.sh
          chmod +x ./scripts/release-scripts/version.sh
          VERSION=$(./scripts/release-scripts/version.sh)
          ./scripts/release-scripts/release.sh --no-snapshots "$VERSION"