name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Build and Upload Release
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Package Release Files
        run: |
          mkdir release
          find . -type f -path "*/target/*.jar" -exec cp {} release/ \;
          zip -r open-banking-gateway-${GITHUB_REF_NAME}.zip release

      - name: Create GitHub Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            open-banking-gateway-${{ github.ref_name }}.zip
        env:
          RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN}}
