@startuml

node core [
    <b>Kernel</b>
    ==
    BPMN engine
    Configurations (bank profile)
    REST API (TPP API)
]

rectangle "Bank-1 plugin" {
    component "XS2A compatible Bank-1 adapter" as bank1
    component "Bank-1 workflow" as workflow1
}

rectangle "Bank-2 plugin" {
    component "XS2A compatible Bank-2 adapter" as bank2
    component "Bank-2 workflow" as workflow2
}

rectangle "Bank-3 plugin" {
    component "HBCI compatible Bank-3 adapter" as bank3
    component "Bank-3 workflow" as workflow3
}

rectangle "Bank-4 plugin" {
    component "Bank-4 adapter" as bank4
    component "Bank-4 workflow" as workflow4
}


workflow1 =right=> core
bank1 =right=> workflow1

workflow2 =left=> core
bank2 =left=> workflow2

workflow3 =left=> core
bank3 =left=> workflow3

workflow4 =left=> core
bank4 =left=> workflow4

bank1 -[hidden]down-> bank2
bank3 -[hidden]down-> bank4

@enduml
