@startuml

node core [
    <b>Kernel</b>
    ==
    Process orchestration: BPMN
    Configuration / bank profiles
    Consent storage
    REST API (TPP API)
]

rectangle "Financier Globe Bank" as xs2aBank1 {
    component "Financier Globe Bank (XS2A) Adapter" as bank1_adapter
    component "Financier workflow" as workflow1
    note left {
        {{
            Consent --> Authorize
            Authorize --> Challenge
            return
            Authorize --> Consent
        }}
    }
    workflow1 --> bank1_adapter
}

rectangle "California Bank & Trust" as xs2aBank2 {
    component "California Bank & Trust adapter (XS2A)" as bank2_adapter
    component "California workflow" as workflow2
    note left {
        {{
            Consent --> Authorize
            return
        }}
    }
    workflow2 --> bank2_adapter
}

rectangle "Cashier Globe Bank" as bank3 {
    component "Cashier Globe Bank adapter (Non-XS2A)" as bank3_adapter
    component "Cashier workflow" as workflow3
    note left {
        {{
            User --> Bank
            return
        }}
    }
    workflow3 --> bank3_adapter
}

xs2aBank1 =right=> core
xs2aBank2 =down=> core
bank3 =up=> core

@enduml
