@startuml

actor "Better Loans (FinTech)" as FinTech
actor "John Doe (PSU)" as PSU

component "TPP REST API" as api
component "REST context" as restContext

component "Banking protocol DB" as db

node initialContext  [
    aspsp-id: 53c47f54
    sca-preferred: EMBEDDED
]

node requestContext [
    aspsp-id: 53c47f54
    username: anton.brueckner
    password: 12345
    sca-preferred: EMBEDDED
    from: 2008-01-01
]

component "BPMN flow for\nFinancier Globe Bank" as bpmn {
    component "Consent initiate\n(Financier Globe Bank class)" as initiate
    component "SCA challenge\n(Financier Globe Bank class)" as challenge
    component "SCA finalize\n(Financier Globe Bank class)" as finalize
    component "Get transaction list\n(Financier Globe Bank class)" as txList

    initiate -down-> challenge
    challenge -down-> finalize
    finalize -down-> txList
}

PSU -down-> FinTech : 1. Give me a loan
FinTech -down-> api : 2. Get transaction\nlist for John Doe
api -down-> db : 3. Read initial context
db -down-> initialContext : 4. Context
initialContext -right-> restContext : 5. Add request\ndata to context
restContext -right-> requestContext : 6. Full context
api -down-> bpmn : 7. Execute flow\nassociated with bank
initiate <-- requestContext : Use\naspsp-id: 53c47f54\nsca-preferred: EMBEDDED
challenge <-- requestContext : Use\nusername: anton.brueckner\npassword: 12345
txList --> api : 8. Transaction list
@enduml
