@startuml

actor "Better Loans (FinTech)" as FinTech
actor "John Doe (PSU)" as PSU
component "TPP REST API" as api

component "BPMN flow management" as bpmn {
    component "BPMN flow for\nFinancier Globe Bank" as flow
}

component "ASPSP api adapter" as aspsp_adapter
component "Financier Globe Bank\nparameter extractor" as aspsp_param_provider
component "Financier Globe Bank (ASPSP)" as aspsp
component "Financier Globe Bank\n mocked\ncontrollers" as aspsp_mocked

PSU -> FinTech : 1. Give me a loan
FinTech -> api : 2. Get transaction\nlist for John Doe
api --> bpmn : 3. Get transaction list
flow <--> aspsp_param_provider : 4. <b>params</b> = Get\nparameters\nfrom CONTEXT
flow --> aspsp_adapter : 5. Get\ntransaction\nlist\nusing <b>params</b>
aspsp_adapter -> aspsp_mocked : 6. Get\ntransaction list
aspsp_mocked -down-> aspsp_adapter : 7. All\nparameters\npresent
aspsp_adapter -up-> flow : 8. All ok
flow --> aspsp_adapter : 9. Get\ntransaction list\nusing <b>params</b>
aspsp_adapter --> aspsp : 10. Get\ntransaction list
aspsp --> aspsp_adapter : 11. User\ntransaction list
aspsp_adapter --> flow : 12. User\ntransaction list
bpmn --> api : 13. User\ntransaction list
api --> FinTech : 14. List


@enduml
